// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto
// Protobuf C++ Version: 5.29.5

#ifndef messages_2eproto_2epb_2eh
#define messages_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_messages_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_messages_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_messages_2eproto;
namespace danasim {
namespace proto {
class SimulationFrame;
struct SimulationFrameDefaultTypeInternal;
extern SimulationFrameDefaultTypeInternal _SimulationFrame_default_instance_;
}  // namespace proto
}  // namespace danasim
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace danasim {
namespace proto {

// ===================================================================


// -------------------------------------------------------------------

class SimulationFrame final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:danasim.proto.SimulationFrame) */ {
 public:
  inline SimulationFrame() : SimulationFrame(nullptr) {}
  ~SimulationFrame() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SimulationFrame* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SimulationFrame));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SimulationFrame(
      ::google::protobuf::internal::ConstantInitialized);

  inline SimulationFrame(const SimulationFrame& from) : SimulationFrame(nullptr, from) {}
  inline SimulationFrame(SimulationFrame&& from) noexcept
      : SimulationFrame(nullptr, std::move(from)) {}
  inline SimulationFrame& operator=(const SimulationFrame& from) {
    CopyFrom(from);
    return *this;
  }
  inline SimulationFrame& operator=(SimulationFrame&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SimulationFrame& default_instance() {
    return *internal_default_instance();
  }
  static inline const SimulationFrame* internal_default_instance() {
    return reinterpret_cast<const SimulationFrame*>(
        &_SimulationFrame_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SimulationFrame& a, SimulationFrame& b) { a.Swap(&b); }
  inline void Swap(SimulationFrame* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SimulationFrame* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SimulationFrame* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SimulationFrame>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SimulationFrame& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SimulationFrame& from) { SimulationFrame::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SimulationFrame* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "danasim.proto.SimulationFrame"; }

 protected:
  explicit SimulationFrame(::google::protobuf::Arena* arena);
  SimulationFrame(::google::protobuf::Arena* arena, const SimulationFrame& from);
  SimulationFrame(::google::protobuf::Arena* arena, SimulationFrame&& from) noexcept
      : SimulationFrame(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kChangedXFieldNumber = 5,
    kChangedYFieldNumber = 6,
    kSimulationTimeFieldNumber = 1,
    kChunkIndexFieldNumber = 2,
    kTotalChunksFieldNumber = 3,
    kIsLastChunkFieldNumber = 4,
  };
  // repeated int64 changed_x = 5;
  int changed_x_size() const;
  private:
  int _internal_changed_x_size() const;

  public:
  void clear_changed_x() ;
  ::int64_t changed_x(int index) const;
  void set_changed_x(int index, ::int64_t value);
  void add_changed_x(::int64_t value);
  const ::google::protobuf::RepeatedField<::int64_t>& changed_x() const;
  ::google::protobuf::RepeatedField<::int64_t>* mutable_changed_x();

  private:
  const ::google::protobuf::RepeatedField<::int64_t>& _internal_changed_x() const;
  ::google::protobuf::RepeatedField<::int64_t>* _internal_mutable_changed_x();

  public:
  // repeated int64 changed_y = 6;
  int changed_y_size() const;
  private:
  int _internal_changed_y_size() const;

  public:
  void clear_changed_y() ;
  ::int64_t changed_y(int index) const;
  void set_changed_y(int index, ::int64_t value);
  void add_changed_y(::int64_t value);
  const ::google::protobuf::RepeatedField<::int64_t>& changed_y() const;
  ::google::protobuf::RepeatedField<::int64_t>* mutable_changed_y();

  private:
  const ::google::protobuf::RepeatedField<::int64_t>& _internal_changed_y() const;
  ::google::protobuf::RepeatedField<::int64_t>* _internal_mutable_changed_y();

  public:
  // string simulation_time = 1;
  void clear_simulation_time() ;
  const std::string& simulation_time() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_simulation_time(Arg_&& arg, Args_... args);
  std::string* mutable_simulation_time();
  PROTOBUF_NODISCARD std::string* release_simulation_time();
  void set_allocated_simulation_time(std::string* value);

  private:
  const std::string& _internal_simulation_time() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_simulation_time(
      const std::string& value);
  std::string* _internal_mutable_simulation_time();

  public:
  // int32 chunk_index = 2;
  void clear_chunk_index() ;
  ::int32_t chunk_index() const;
  void set_chunk_index(::int32_t value);

  private:
  ::int32_t _internal_chunk_index() const;
  void _internal_set_chunk_index(::int32_t value);

  public:
  // int32 total_chunks = 3;
  void clear_total_chunks() ;
  ::int32_t total_chunks() const;
  void set_total_chunks(::int32_t value);

  private:
  ::int32_t _internal_total_chunks() const;
  void _internal_set_total_chunks(::int32_t value);

  public:
  // bool is_last_chunk = 4;
  void clear_is_last_chunk() ;
  bool is_last_chunk() const;
  void set_is_last_chunk(bool value);

  private:
  bool _internal_is_last_chunk() const;
  void _internal_set_is_last_chunk(bool value);

  public:
  // @@protoc_insertion_point(class_scope:danasim.proto.SimulationFrame)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 6, 0,
      53, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SimulationFrame& from_msg);
    ::google::protobuf::RepeatedField<::int64_t> changed_x_;
    ::google::protobuf::internal::CachedSize _changed_x_cached_byte_size_;
    ::google::protobuf::RepeatedField<::int64_t> changed_y_;
    ::google::protobuf::internal::CachedSize _changed_y_cached_byte_size_;
    ::google::protobuf::internal::ArenaStringPtr simulation_time_;
    ::int32_t chunk_index_;
    ::int32_t total_chunks_;
    bool is_last_chunk_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_messages_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SimulationFrame

// string simulation_time = 1;
inline void SimulationFrame::clear_simulation_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.simulation_time_.ClearToEmpty();
}
inline const std::string& SimulationFrame::simulation_time() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:danasim.proto.SimulationFrame.simulation_time)
  return _internal_simulation_time();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SimulationFrame::set_simulation_time(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.simulation_time_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:danasim.proto.SimulationFrame.simulation_time)
}
inline std::string* SimulationFrame::mutable_simulation_time() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_simulation_time();
  // @@protoc_insertion_point(field_mutable:danasim.proto.SimulationFrame.simulation_time)
  return _s;
}
inline const std::string& SimulationFrame::_internal_simulation_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.simulation_time_.Get();
}
inline void SimulationFrame::_internal_set_simulation_time(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.simulation_time_.Set(value, GetArena());
}
inline std::string* SimulationFrame::_internal_mutable_simulation_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.simulation_time_.Mutable( GetArena());
}
inline std::string* SimulationFrame::release_simulation_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:danasim.proto.SimulationFrame.simulation_time)
  return _impl_.simulation_time_.Release();
}
inline void SimulationFrame::set_allocated_simulation_time(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.simulation_time_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.simulation_time_.IsDefault()) {
    _impl_.simulation_time_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:danasim.proto.SimulationFrame.simulation_time)
}

// int32 chunk_index = 2;
inline void SimulationFrame::clear_chunk_index() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.chunk_index_ = 0;
}
inline ::int32_t SimulationFrame::chunk_index() const {
  // @@protoc_insertion_point(field_get:danasim.proto.SimulationFrame.chunk_index)
  return _internal_chunk_index();
}
inline void SimulationFrame::set_chunk_index(::int32_t value) {
  _internal_set_chunk_index(value);
  // @@protoc_insertion_point(field_set:danasim.proto.SimulationFrame.chunk_index)
}
inline ::int32_t SimulationFrame::_internal_chunk_index() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.chunk_index_;
}
inline void SimulationFrame::_internal_set_chunk_index(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.chunk_index_ = value;
}

// int32 total_chunks = 3;
inline void SimulationFrame::clear_total_chunks() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.total_chunks_ = 0;
}
inline ::int32_t SimulationFrame::total_chunks() const {
  // @@protoc_insertion_point(field_get:danasim.proto.SimulationFrame.total_chunks)
  return _internal_total_chunks();
}
inline void SimulationFrame::set_total_chunks(::int32_t value) {
  _internal_set_total_chunks(value);
  // @@protoc_insertion_point(field_set:danasim.proto.SimulationFrame.total_chunks)
}
inline ::int32_t SimulationFrame::_internal_total_chunks() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.total_chunks_;
}
inline void SimulationFrame::_internal_set_total_chunks(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.total_chunks_ = value;
}

// bool is_last_chunk = 4;
inline void SimulationFrame::clear_is_last_chunk() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_last_chunk_ = false;
}
inline bool SimulationFrame::is_last_chunk() const {
  // @@protoc_insertion_point(field_get:danasim.proto.SimulationFrame.is_last_chunk)
  return _internal_is_last_chunk();
}
inline void SimulationFrame::set_is_last_chunk(bool value) {
  _internal_set_is_last_chunk(value);
  // @@protoc_insertion_point(field_set:danasim.proto.SimulationFrame.is_last_chunk)
}
inline bool SimulationFrame::_internal_is_last_chunk() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_last_chunk_;
}
inline void SimulationFrame::_internal_set_is_last_chunk(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_last_chunk_ = value;
}

// repeated int64 changed_x = 5;
inline int SimulationFrame::_internal_changed_x_size() const {
  return _internal_changed_x().size();
}
inline int SimulationFrame::changed_x_size() const {
  return _internal_changed_x_size();
}
inline void SimulationFrame::clear_changed_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.changed_x_.Clear();
}
inline ::int64_t SimulationFrame::changed_x(int index) const {
  // @@protoc_insertion_point(field_get:danasim.proto.SimulationFrame.changed_x)
  return _internal_changed_x().Get(index);
}
inline void SimulationFrame::set_changed_x(int index, ::int64_t value) {
  _internal_mutable_changed_x()->Set(index, value);
  // @@protoc_insertion_point(field_set:danasim.proto.SimulationFrame.changed_x)
}
inline void SimulationFrame::add_changed_x(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_changed_x()->Add(value);
  // @@protoc_insertion_point(field_add:danasim.proto.SimulationFrame.changed_x)
}
inline const ::google::protobuf::RepeatedField<::int64_t>& SimulationFrame::changed_x() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:danasim.proto.SimulationFrame.changed_x)
  return _internal_changed_x();
}
inline ::google::protobuf::RepeatedField<::int64_t>* SimulationFrame::mutable_changed_x()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:danasim.proto.SimulationFrame.changed_x)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_changed_x();
}
inline const ::google::protobuf::RepeatedField<::int64_t>&
SimulationFrame::_internal_changed_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.changed_x_;
}
inline ::google::protobuf::RepeatedField<::int64_t>* SimulationFrame::_internal_mutable_changed_x() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.changed_x_;
}

// repeated int64 changed_y = 6;
inline int SimulationFrame::_internal_changed_y_size() const {
  return _internal_changed_y().size();
}
inline int SimulationFrame::changed_y_size() const {
  return _internal_changed_y_size();
}
inline void SimulationFrame::clear_changed_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.changed_y_.Clear();
}
inline ::int64_t SimulationFrame::changed_y(int index) const {
  // @@protoc_insertion_point(field_get:danasim.proto.SimulationFrame.changed_y)
  return _internal_changed_y().Get(index);
}
inline void SimulationFrame::set_changed_y(int index, ::int64_t value) {
  _internal_mutable_changed_y()->Set(index, value);
  // @@protoc_insertion_point(field_set:danasim.proto.SimulationFrame.changed_y)
}
inline void SimulationFrame::add_changed_y(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_changed_y()->Add(value);
  // @@protoc_insertion_point(field_add:danasim.proto.SimulationFrame.changed_y)
}
inline const ::google::protobuf::RepeatedField<::int64_t>& SimulationFrame::changed_y() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:danasim.proto.SimulationFrame.changed_y)
  return _internal_changed_y();
}
inline ::google::protobuf::RepeatedField<::int64_t>* SimulationFrame::mutable_changed_y()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:danasim.proto.SimulationFrame.changed_y)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_changed_y();
}
inline const ::google::protobuf::RepeatedField<::int64_t>&
SimulationFrame::_internal_changed_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.changed_y_;
}
inline ::google::protobuf::RepeatedField<::int64_t>* SimulationFrame::_internal_mutable_changed_y() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.changed_y_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace danasim


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // messages_2eproto_2epb_2eh
