// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto
// Protobuf C++ Version: 5.29.5

#include "messages.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace danasim {
namespace proto {

inline constexpr SimulationFrame::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : changed_x_{},
        _changed_x_cached_byte_size_{0},
        changed_y_{},
        _changed_y_cached_byte_size_{0},
        simulation_time_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        chunk_index_{0},
        total_chunks_{0},
        is_last_chunk_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SimulationFrame::SimulationFrame(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SimulationFrameDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SimulationFrameDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SimulationFrameDefaultTypeInternal() {}
  union {
    SimulationFrame _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SimulationFrameDefaultTypeInternal _SimulationFrame_default_instance_;
}  // namespace proto
}  // namespace danasim
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_messages_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_messages_2eproto = nullptr;
const ::uint32_t
    TableStruct_messages_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::danasim::proto::SimulationFrame, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::danasim::proto::SimulationFrame, _impl_.simulation_time_),
        PROTOBUF_FIELD_OFFSET(::danasim::proto::SimulationFrame, _impl_.chunk_index_),
        PROTOBUF_FIELD_OFFSET(::danasim::proto::SimulationFrame, _impl_.total_chunks_),
        PROTOBUF_FIELD_OFFSET(::danasim::proto::SimulationFrame, _impl_.is_last_chunk_),
        PROTOBUF_FIELD_OFFSET(::danasim::proto::SimulationFrame, _impl_.changed_x_),
        PROTOBUF_FIELD_OFFSET(::danasim::proto::SimulationFrame, _impl_.changed_y_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::danasim::proto::SimulationFrame)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::danasim::proto::_SimulationFrame_default_instance_._instance,
};
const char descriptor_table_protodef_messages_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016messages.proto\022\rdanasim.proto\"\222\001\n\017Simu"
    "lationFrame\022\027\n\017simulation_time\030\001 \001(\t\022\023\n\013"
    "chunk_index\030\002 \001(\005\022\024\n\014total_chunks\030\003 \001(\005\022"
    "\025\n\ris_last_chunk\030\004 \001(\010\022\021\n\tchanged_x\030\005 \003("
    "\003\022\021\n\tchanged_y\030\006 \003(\003b\006proto3"
};
static ::absl::once_flag descriptor_table_messages_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_messages_2eproto = {
    false,
    false,
    188,
    descriptor_table_protodef_messages_2eproto,
    "messages.proto",
    &descriptor_table_messages_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_messages_2eproto::offsets,
    file_level_enum_descriptors_messages_2eproto,
    file_level_service_descriptors_messages_2eproto,
};
namespace danasim {
namespace proto {
// ===================================================================

class SimulationFrame::_Internal {
 public:
};

SimulationFrame::SimulationFrame(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:danasim.proto.SimulationFrame)
}
inline PROTOBUF_NDEBUG_INLINE SimulationFrame::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::danasim::proto::SimulationFrame& from_msg)
      : changed_x_{visibility, arena, from.changed_x_},
        _changed_x_cached_byte_size_{0},
        changed_y_{visibility, arena, from.changed_y_},
        _changed_y_cached_byte_size_{0},
        simulation_time_(arena, from.simulation_time_),
        _cached_size_{0} {}

SimulationFrame::SimulationFrame(
    ::google::protobuf::Arena* arena,
    const SimulationFrame& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SimulationFrame* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, chunk_index_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, chunk_index_),
           offsetof(Impl_, is_last_chunk_) -
               offsetof(Impl_, chunk_index_) +
               sizeof(Impl_::is_last_chunk_));

  // @@protoc_insertion_point(copy_constructor:danasim.proto.SimulationFrame)
}
inline PROTOBUF_NDEBUG_INLINE SimulationFrame::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : changed_x_{visibility, arena},
        _changed_x_cached_byte_size_{0},
        changed_y_{visibility, arena},
        _changed_y_cached_byte_size_{0},
        simulation_time_(arena),
        _cached_size_{0} {}

inline void SimulationFrame::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, chunk_index_),
           0,
           offsetof(Impl_, is_last_chunk_) -
               offsetof(Impl_, chunk_index_) +
               sizeof(Impl_::is_last_chunk_));
}
SimulationFrame::~SimulationFrame() {
  // @@protoc_insertion_point(destructor:danasim.proto.SimulationFrame)
  SharedDtor(*this);
}
inline void SimulationFrame::SharedDtor(MessageLite& self) {
  SimulationFrame& this_ = static_cast<SimulationFrame&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.simulation_time_.Destroy();
  this_._impl_.~Impl_();
}

inline void* SimulationFrame::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SimulationFrame(arena);
}
constexpr auto SimulationFrame::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(SimulationFrame, _impl_.changed_x_) +
          decltype(SimulationFrame::_impl_.changed_x_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(SimulationFrame, _impl_.changed_y_) +
          decltype(SimulationFrame::_impl_.changed_y_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(SimulationFrame), alignof(SimulationFrame), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&SimulationFrame::PlacementNew_,
                                 sizeof(SimulationFrame),
                                 alignof(SimulationFrame));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SimulationFrame::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SimulationFrame_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SimulationFrame::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SimulationFrame>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SimulationFrame::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SimulationFrame>(), &SimulationFrame::ByteSizeLong,
            &SimulationFrame::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SimulationFrame, _impl_._cached_size_),
        false,
    },
    &SimulationFrame::kDescriptorMethods,
    &descriptor_table_messages_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SimulationFrame::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 53, 2> SimulationFrame::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::danasim::proto::SimulationFrame>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string simulation_time = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(SimulationFrame, _impl_.simulation_time_)}},
    // int32 chunk_index = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SimulationFrame, _impl_.chunk_index_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(SimulationFrame, _impl_.chunk_index_)}},
    // int32 total_chunks = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SimulationFrame, _impl_.total_chunks_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(SimulationFrame, _impl_.total_chunks_)}},
    // bool is_last_chunk = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SimulationFrame, _impl_.is_last_chunk_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(SimulationFrame, _impl_.is_last_chunk_)}},
    // repeated int64 changed_x = 5;
    {::_pbi::TcParser::FastV64P1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(SimulationFrame, _impl_.changed_x_)}},
    // repeated int64 changed_y = 6;
    {::_pbi::TcParser::FastV64P1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(SimulationFrame, _impl_.changed_y_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string simulation_time = 1;
    {PROTOBUF_FIELD_OFFSET(SimulationFrame, _impl_.simulation_time_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 chunk_index = 2;
    {PROTOBUF_FIELD_OFFSET(SimulationFrame, _impl_.chunk_index_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 total_chunks = 3;
    {PROTOBUF_FIELD_OFFSET(SimulationFrame, _impl_.total_chunks_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // bool is_last_chunk = 4;
    {PROTOBUF_FIELD_OFFSET(SimulationFrame, _impl_.is_last_chunk_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // repeated int64 changed_x = 5;
    {PROTOBUF_FIELD_OFFSET(SimulationFrame, _impl_.changed_x_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt64)},
    // repeated int64 changed_y = 6;
    {PROTOBUF_FIELD_OFFSET(SimulationFrame, _impl_.changed_y_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt64)},
  }},
  // no aux_entries
  {{
    "\35\17\0\0\0\0\0\0"
    "danasim.proto.SimulationFrame"
    "simulation_time"
  }},
};

PROTOBUF_NOINLINE void SimulationFrame::Clear() {
// @@protoc_insertion_point(message_clear_start:danasim.proto.SimulationFrame)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.changed_x_.Clear();
  _impl_.changed_y_.Clear();
  _impl_.simulation_time_.ClearToEmpty();
  ::memset(&_impl_.chunk_index_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.is_last_chunk_) -
      reinterpret_cast<char*>(&_impl_.chunk_index_)) + sizeof(_impl_.is_last_chunk_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SimulationFrame::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SimulationFrame& this_ = static_cast<const SimulationFrame&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SimulationFrame::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SimulationFrame& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:danasim.proto.SimulationFrame)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string simulation_time = 1;
          if (!this_._internal_simulation_time().empty()) {
            const std::string& _s = this_._internal_simulation_time();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "danasim.proto.SimulationFrame.simulation_time");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // int32 chunk_index = 2;
          if (this_._internal_chunk_index() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_chunk_index(), target);
          }

          // int32 total_chunks = 3;
          if (this_._internal_total_chunks() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_total_chunks(), target);
          }

          // bool is_last_chunk = 4;
          if (this_._internal_is_last_chunk() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                4, this_._internal_is_last_chunk(), target);
          }

          // repeated int64 changed_x = 5;
          {
            int byte_size = this_._impl_._changed_x_cached_byte_size_.Get();
            if (byte_size > 0) {
              target = stream->WriteInt64Packed(
                  5, this_._internal_changed_x(), byte_size, target);
            }
          }

          // repeated int64 changed_y = 6;
          {
            int byte_size = this_._impl_._changed_y_cached_byte_size_.Get();
            if (byte_size > 0) {
              target = stream->WriteInt64Packed(
                  6, this_._internal_changed_y(), byte_size, target);
            }
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:danasim.proto.SimulationFrame)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SimulationFrame::ByteSizeLong(const MessageLite& base) {
          const SimulationFrame& this_ = static_cast<const SimulationFrame&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SimulationFrame::ByteSizeLong() const {
          const SimulationFrame& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:danasim.proto.SimulationFrame)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated int64 changed_x = 5;
            {
              total_size +=
                  ::_pbi::WireFormatLite::Int64SizeWithPackedTagSize(
                      this_._internal_changed_x(), 1,
                      this_._impl_._changed_x_cached_byte_size_);
            }
            // repeated int64 changed_y = 6;
            {
              total_size +=
                  ::_pbi::WireFormatLite::Int64SizeWithPackedTagSize(
                      this_._internal_changed_y(), 1,
                      this_._impl_._changed_y_cached_byte_size_);
            }
          }
           {
            // string simulation_time = 1;
            if (!this_._internal_simulation_time().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_simulation_time());
            }
            // int32 chunk_index = 2;
            if (this_._internal_chunk_index() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_chunk_index());
            }
            // int32 total_chunks = 3;
            if (this_._internal_total_chunks() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_total_chunks());
            }
            // bool is_last_chunk = 4;
            if (this_._internal_is_last_chunk() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SimulationFrame::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SimulationFrame*>(&to_msg);
  auto& from = static_cast<const SimulationFrame&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:danasim.proto.SimulationFrame)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_changed_x()->MergeFrom(from._internal_changed_x());
  _this->_internal_mutable_changed_y()->MergeFrom(from._internal_changed_y());
  if (!from._internal_simulation_time().empty()) {
    _this->_internal_set_simulation_time(from._internal_simulation_time());
  }
  if (from._internal_chunk_index() != 0) {
    _this->_impl_.chunk_index_ = from._impl_.chunk_index_;
  }
  if (from._internal_total_chunks() != 0) {
    _this->_impl_.total_chunks_ = from._impl_.total_chunks_;
  }
  if (from._internal_is_last_chunk() != 0) {
    _this->_impl_.is_last_chunk_ = from._impl_.is_last_chunk_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SimulationFrame::CopyFrom(const SimulationFrame& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:danasim.proto.SimulationFrame)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SimulationFrame::InternalSwap(SimulationFrame* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.changed_x_.InternalSwap(&other->_impl_.changed_x_);
  _impl_.changed_y_.InternalSwap(&other->_impl_.changed_y_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.simulation_time_, &other->_impl_.simulation_time_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SimulationFrame, _impl_.is_last_chunk_)
      + sizeof(SimulationFrame::_impl_.is_last_chunk_)
      - PROTOBUF_FIELD_OFFSET(SimulationFrame, _impl_.chunk_index_)>(
          reinterpret_cast<char*>(&_impl_.chunk_index_),
          reinterpret_cast<char*>(&other->_impl_.chunk_index_));
}

::google::protobuf::Metadata SimulationFrame::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace danasim
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_messages_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
