scenario:
  output_dir: /kaggle/working
  name: scenario_29_10_2024
  append_start_timestamp: false

logging:
  level: Info
  async: false
  silent: false
  save_log_file: true

input:
  file:
    static_format: Idrisi
    dynamic_format: Hif
    dataset_folder: /kaggle/working/data
    dataset_name: data_29_10_2024_ver_3_check_9
  scalars:
    fluid_density: 1000.0
    fluid_viscosity: 0.001

output:
  snapshot:
    every_n_steps: 1200
  outputs:
    - type: Mqtt
      protocol: mqtt://
      host: 127.0.0.1
      port: 1883
      format: Json
      send_initial_state: false
    - type: Checkpoint
      static_format: Idrisi

state_updater:
  enable_rainfall: true
  dry_tolerance: 0.001
  flood_risk:
    default_level:
      name: Dry
      color_hex: F5DEB3FF
    levels:
      - name: Level 1
        threshold_start: 0.2
        color_hex: "#FFF176FF"
      - name: Level 2
        threshold_start: 0.4
        color_hex: "#FFD54FFF"
      - name: Level 3
        threshold_start: 0.6
        color_hex: "#FFB74DFF"
      - name: Level 4
        threshold_start: 0.8
        color_hex: "#FFA726FF"
      - name: Level 5
        threshold_start: 1
        color_hex: "#FF8A65FF"
      - name: Level 6
        threshold_start: 1.2
        color_hex: "#FF7043FF"
      - name: Level 7
        threshold_start: 1.4
        color_hex: "#F4511EFF"
      - name: Level 8
        threshold_start: 1.6
        color_hex: "#E64A19FF"
      - name: Level 9
        threshold_start: 1.8
        color_hex: "#D84315FF"
      - name: Level 10
        threshold_start: 2
        color_hex: "#E53935FF"
      - name: Level 11
        threshold_start: 2.5
        color_hex: "#C62828FF"
      - name: Level 12
        threshold_start: 3.5
        color_hex: "#B71C1CFF"
      - name: Level 13
        threshold_start: 5
        color_hex: "#880E4FFF"
      - name: Level 14
        threshold_start: 8
        color_hex: "#4A148CFF"
      - name: Level 15
        threshold_start: 12
        color_hex: "#1A001AFF"
  updater:
    type: Onnx
    model_path: /usr/share/floodsim/exported_models/first_model_cpu
    tensor_dim: 16

simulation:
  start_timestamp: 2024-10-29T13:00:00
  time_step: 00:00:00.25
  duration: 00:20:00
  view_box: 
    use_full_grid: true
    south_west:
      lon: -0.78291248
      lat: 39.32434531
    north_east:
      lon: -0.22811569
      lat: 39.56367382