scenario:
  outputDir: ../outputs
  name: scenario_29_10_2024_kaggle

logging:
  level: info
  async: true
  silent: false
  saveLogFile: true

input:
  type: file
  path: /kaggle/input/sim-data/data_29_10_2024

output:
  snapshot:
    every_n_steps: 60
  outputs:
    - type: image

state_updater:
  type: onnx
  model_path: ../models/simulation_model_cpu.onnx

simulation:
  time_step: 1.0
  total_time: 28800.0
  view_min_x: 700000.0
  view_max_x: 740000.0
  view_min_y: 4365000.0
  view_max_y: 4375000.0