scenario:
  outputDir: ../outputs
  name: scenario_29_10_2024

logging:
  level: info
  async: true
  silent: false
  saveLogFile: true

input:
  sources:
    - type: file
      static_format: IDRISI
      dynamic_format: HIF
      path: ../data/data_29_10_2024
  layers:
    - name: elevation
      source: file
    - name: water_depth
      source: file
    - name: roughness
      source: file
    - name: rainfall
      source: file

output:
  snapshot:
    every_n_steps: 2
  outputs:
    - type: image

state_updater:
  type: onnx
  model_path: ../models/simulation_model_cpu.onnx

simulation:
  start_timestamp: 2024-10-29T10:00:00
  time_step: 00:00:01
  duration: 08:00:00
  view_box: 
    use_full_grid: true
    south_west:
      lon: -0.78291248
      lat: 39.32434531
    north_east:
      lon: -0.22811569
      lat: 39.56367382