scenario:
  outputDir: ../outputs
  name: scenario_29_10_2024

logging:
  level: info
  async: false
  silent: false
  saveLogFile: true

input:
  file:
    static_format: IDRISI
    dynamic_format: HIF
    path: ../data/data_29_10_2024
  scalars:
    - name: fluid_density
      value: 1000.0
    - name: fluid_viscosity
      value: 0.001

output:
  snapshot:
    every_n_steps: 10
  outputs:
    - type: image

state_updater:
  type: onnx
  model_path: ../exported_models/first_model_cpu
  tensor_dim: 16

simulation:
  start_timestamp: 2024-10-29T10:00:00
  time_step: 00:00:01
  duration: 08:00:00
  view_box: 
    use_full_grid: true
    south_west:
      lon: -0.78291248
      lat: 39.32434531
    north_east:
      lon: -0.22811569
      lat: 39.56367382