scenario:
  output_dir: /kaggle/working
  name: scenario_29_10_2024
  append_start_timestamp: false

logging:
  level: info
  async: false
  silent: false
  save_log_file: true

input:
  file:
    static_format: IDRISI
    dynamic_format: HIF
    dataset_folder: /kaggle/working/data
    dataset_name: data_29_10_2024_check_2
  scalars:
    fluid_density: 1000.0
    fluid_viscosity: 0.001

output:
  snapshot:
    every_n_steps: 900
  outputs:
    - type: MQTT
      protocol: mqtt://
      host: 127.0.0.1
      port: 1883
      format: JSON
    - type: CHECKPOINT
      static_format: IDRISI

state_updater:
  enable_rainfall: true
  dry_tolerance: 0.001
  flood_risk:
    default_level:
      name: Dry
      color_hex: F5DEB3FF
    levels:
      - name: Very Shallow
        threshold_start: 0.001
        color_hex: E0F3F8FF
      - name: Low Depth
        threshold_start: 0.1
        color_hex: 87CEEBFF
      - name: Medium Depth
        threshold_start: 0.3
        color_hex: 1E90FFFF
      - name: High Depth
        threshold_start: 1.0
        color_hex: 0000CDFF
      - name: Extreme Depth
        threshold_start: 2.0
        color_hex: 4B0082FF
  updater:
    type: ONNX
    model_path: /usr/share/floodsim/exported_models/first_model_cpu
    tensor_dim: 16

simulation:
  start_timestamp: 2024-10-29T13:15:00
  time_step: 00:00:01
  duration: 04:00:00
  view_box: 
    use_full_grid: true
    south_west:
      lon: -0.78291248
      lat: 39.32434531
    north_east:
      lon: -0.22811569
      lat: 39.56367382