logging:
  level: Debug
  async: false
  silent: false
  save_log_file: true
scenario:
  name: scenario_29_10_2024
  output_dir: C:\Devs\DanaSim\outputs
  append_start_timestamp: false
simulation:
  start_timestamp: 2024-10-29T10:00:00
  time_step: 00:00:01
  duration: 04:00:00
  view_box:
    use_full_grid: true
    south_west:
      lon: 0
      lat: 0
    north_east:
      lon: 0
      lat: 0
state_updater:
  enable_rainfall: true
  dry_tolerance: 0.00100000005
  flood_risk:
    default_level:
      name: Dry
      color_hex: F5DEB3FF
    levels:
      - name: Very Shallow
        threshold_start: 0.00100000005
        color_hex: E0F3F8FF
      - name: Low Depth
        threshold_start: 0.100000001
        color_hex: 87CEEBFF
      - name: Medium Depth
        threshold_start: 0.300000012
        color_hex: 1E90FFFF
      - name: High Depth
        threshold_start: 1
        color_hex: 0000CDFF
      - name: Extreme Depth
        threshold_start: 2
        color_hex: 4B0082FF
  updater:
    type: Onnx
    model_path: C:\Devs\DanaSim\exported_models\first_model_cpu
    tensor_dim: 16
input:
  file:
    dataset_folder: C:\Devs\DanaSim\data
    dataset_name: data_29_10_2024
    static_format: Idrisi
    dynamic_format: Hif
  scalars:
    fluid_density: 1000.0
    fluid_viscosity: 0.001
output:
  snapshot:
    every_n_steps: 30
  outputs:
    - type: Image