scenario:
  name: second_data_1

logging:
  level: debug
  async: false
  silent: false
  file: simulation.log

input:
  type: file
  path: ../../../data/first_data

output:
  snapshot:
    every_n_steps: 1
  outputs:
    - type: mqtt
      address: tcp://localhost:1883
      topic: danasim/updates
      client_id: Simulation_Publisher_Node
      qos: 1
      format: protobuf

state_updater:
  type: tensorflow
  model_path: ../../../models

simulation:
  time_step: 1.0
  total_time: 5.0