scenario:
  outputDir: ../outputs
  name: second_data_1

logging:
  level: debug
  async: false
  silent: false
  saveLogFile: true

input:
  type: file
  path: ../data/first_data

output:
  snapshot:
    every_n_steps: 1
  outputs:
    - type: mqtt
      address: tcp://localhost:1883
      topic: danasim/updates
      client_id: Simulation_Publisher_Node
      qos: 1
      format: protobuf

state_updater:
  type: onnx
  model_path: ../models/simulation_model_cpu.onnx

simulation:
  time_step: 1.0
  total_time: 5.0