scenario:
  outputDir: ../outputs
  name: second_data_1

logging:
  level: info
  async: true
  silent: false
  saveLogFile: true

input:
  type: file
  path: ../data/second_data

output:
  snapshot:
    every_n_steps: 180
  outputs:
    - type: image

state_updater:
  type: onnx
  model_path: ../models/simulation_model_cpu.onnx

simulation:
  time_step: 10.0
  total_time: 18000.0