start_date: "2024-10-29 10:00:00"
end_date: "2024-10-30 00:00:00"
output_name: "data_new"
output_dir: "./output"
layers:
  elevation:
    resolution: 5
    bounding_box:
      south_west:
        lon: -0.78291248
        lat: 39.32434531
      north_east:
        lon: -0.22811569
        lat: 39.56367382

  water_depth:

  roughness:

  rainfall:
    simulation:
      time_step: "01:00:00"
    geography:
      downgrade_factor: 5
    interpolation:
      variogram_model: "Spherical"
      min_points_required: 5

visualize:
  enable: True
  layers:
    - "elevation"
    - "rainfall" 