--  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
--  Generated by TASTE (kazoo/templates/skeletons/ada-ri-source/function.tmplt)
with Danasim_Dataview; use Danasim_Dataview;
with Taste_Basictypes; use Taste_Basictypes;
with System_Dataview;  use System_Dataview;
with adaasn1rtl;
with Interfaces.C.Strings; use Interfaces.C.Strings;
with System_Dataview; use System_Dataview;  --  contains definition of the PID type

package Coreengineca_RI is

   procedure Simulationcompleted (Dest_PID : asn1SccPID := asn1sccEnv);
   
   
   procedure Updategridrequest (Griddata : in out asn1SccGriddata; Dest_PID : asn1sccPID := asn1sccEnv);

   procedure Check_Queue (Res : out adaasn1rtl.Asn1Boolean)
      with Import, Convention => C, Link_Name => "coreengineca_check_queue";

   procedure Get_Sender (Sender : out asn1sccPID; Dest_PID : asn1SccPID := asn1sccEnv)
      with Import, Convention => C, Link_Name => "coreengineca_get_sender";

   procedure Get_Last_Error (Err : out asn1sccT_Runtime_Error; Dest_PID : asn1SccPID := asn1sccEnv)
      with Import, Convention => C, Link_Name => "coreengineca_get_last_error";

   --  Fixed number of instances: they cannot be deleted
   procedure Delete_Instance (unused_pid : asn1SccPID) is null;

   --  Return the SDL state as a char * for the MSC tracing function
   function To_C_Pointer (State_As_String : String) return Chars_Ptr is
      (New_String (State_As_String));
end Coreengineca_RI;
