#ifndef GENERATED_ASN1SCC_dataview_uniq_H
#define GENERATED_ASN1SCC_dataview_uniq_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "asn1crt_encoding.h"


#ifdef  __cplusplus
extern "C" {
#endif


typedef asn1Real asn1SccT_Real32;


flag asn1SccT_Real32_Equal(const asn1SccT_Real32* pVal1, const asn1SccT_Real32* pVal2);

#define ERR_T_REAL32		1  /*(-2147483648.0 .. 2147483647.0)*/
flag asn1SccT_Real32_IsConstraintValid(const asn1SccT_Real32* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_Real32 asn1SccT_Real32_constant;
#else
#define asn1SccT_Real32_constant 0.0000000000000000000E+000
#endif

void asn1SccT_Real32_Initialize(asn1SccT_Real32* pVal);

#define ERR_UPER_ENCODE_T_REAL32		2  /**/
#define asn1SccT_Real32_REQUIRED_BYTES_FOR_ENCODING       13
#define asn1SccT_Real32_REQUIRED_BITS_FOR_ENCODING        104

flag asn1SccT_Real32_Encode(const asn1SccT_Real32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_REAL32		3  /**/
flag asn1SccT_Real32_Decode(asn1SccT_Real32* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_Real32_REQUIRED_BYTES_FOR_ACN_ENCODING       13
#define asn1SccT_Real32_REQUIRED_BITS_FOR_ACN_ENCODING        104

#define ERR_ACN_ENCODE_T_REAL32		4  /**/

flag asn1SccT_Real32_ACN_Encode(const asn1SccT_Real32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_REAL32		5  /**/
flag asn1SccT_Real32_ACN_Decode(asn1SccT_Real32* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1Real asn1SccT_UReal32;


flag asn1SccT_UReal32_Equal(const asn1SccT_UReal32* pVal1, const asn1SccT_UReal32* pVal2);

#define ERR_T_UREAL32		6  /*(0.0 .. 4294967294.0)*/
flag asn1SccT_UReal32_IsConstraintValid(const asn1SccT_UReal32* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_UReal32 asn1SccT_UReal32_constant;
#else
#define asn1SccT_UReal32_constant 0.0000000000000000000E+000
#endif

void asn1SccT_UReal32_Initialize(asn1SccT_UReal32* pVal);

#define ERR_UPER_ENCODE_T_UREAL32		7  /**/
#define asn1SccT_UReal32_REQUIRED_BYTES_FOR_ENCODING       13
#define asn1SccT_UReal32_REQUIRED_BITS_FOR_ENCODING        104

flag asn1SccT_UReal32_Encode(const asn1SccT_UReal32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_UREAL32		8  /**/
flag asn1SccT_UReal32_Decode(asn1SccT_UReal32* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_UReal32_REQUIRED_BYTES_FOR_ACN_ENCODING       13
#define asn1SccT_UReal32_REQUIRED_BITS_FOR_ACN_ENCODING        104

#define ERR_ACN_ENCODE_T_UREAL32		9  /**/

flag asn1SccT_UReal32_ACN_Encode(const asn1SccT_UReal32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_UREAL32		10  /**/
flag asn1SccT_UReal32_ACN_Decode(asn1SccT_UReal32* pVal, BitStream* pBitStrm, int* pErrCode);
typedef enum {
    SurfaceType_soil = 0,
    SurfaceType_rock = 1,
    SurfaceType_asphalt = 2,
    SurfaceType_forest = 3,
    SurfaceType_waterSurface = 4
} asn1SccSurfaceType;

// please use the following macros to avoid breaking code.
#define asn1SccSurfaceType_soil SurfaceType_soil
#define asn1SccSurfaceType_rock SurfaceType_rock
#define asn1SccSurfaceType_asphalt SurfaceType_asphalt
#define asn1SccSurfaceType_forest SurfaceType_forest
#define asn1SccSurfaceType_waterSurface SurfaceType_waterSurface

flag asn1SccSurfaceType_Equal(const asn1SccSurfaceType* pVal1, const asn1SccSurfaceType* pVal2);

#define ERR_SURFACETYPE		11  /*soil | rock | asphalt | forest | waterSurface*/
flag asn1SccSurfaceType_IsConstraintValid(const asn1SccSurfaceType* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccSurfaceType asn1SccSurfaceType_constant;
#else
#define asn1SccSurfaceType_constant SurfaceType_soil
#endif

void asn1SccSurfaceType_Initialize(asn1SccSurfaceType* pVal);

#define ERR_UPER_ENCODE_SURFACETYPE		12  /**/
#define asn1SccSurfaceType_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccSurfaceType_REQUIRED_BITS_FOR_ENCODING        3

flag asn1SccSurfaceType_Encode(const asn1SccSurfaceType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_SURFACETYPE		13  /**/
flag asn1SccSurfaceType_Decode(asn1SccSurfaceType* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccSurfaceType_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccSurfaceType_REQUIRED_BITS_FOR_ACN_ENCODING        3

#define ERR_ACN_ENCODE_SURFACETYPE		14  /**/

flag asn1SccSurfaceType_ACN_Encode(const asn1SccSurfaceType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_SURFACETYPE		15  /**/
flag asn1SccSurfaceType_ACN_Decode(asn1SccSurfaceType* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- asn1SccCellState --------------------------------------------*/
typedef struct {
    asn1Real elevation;
    asn1Real waterVolume;
    asn1SccSurfaceType surfaceType;

} asn1SccCellState;

flag asn1SccCellState_Equal(const asn1SccCellState* pVal1, const asn1SccCellState* pVal2);

#define ERR_CELLSTATE		36  /**/
#define ERR_CELLSTATE_ELEVATION		16  /*(0.0 .. 1000.0)*/
#define ERR_CELLSTATE_WATERVOLUME		21  /*(0.0 .. 1000.0)*/
#define ERR_CELLSTATE_SURFACETYPE_2		31  /**/
flag asn1SccCellState_IsConstraintValid(const asn1SccCellState* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccCellState asn1SccCellState_constant;
#else
#define asn1SccCellState_constant {.elevation = 0.0000000000000000000E+000, .waterVolume = 0.0000000000000000000E+000, .surfaceType = SurfaceType_soil}
#endif

void asn1SccCellState_Initialize(asn1SccCellState* pVal);

#define ERR_UPER_ENCODE_CELLSTATE		37  /**/
#define ERR_UPER_ENCODE_CELLSTATE_ELEVATION		17  /**/
#define ERR_UPER_ENCODE_CELLSTATE_WATERVOLUME		22  /**/
#define ERR_UPER_ENCODE_CELLSTATE_SURFACETYPE_2		32  /**/
#define asn1SccCellState_REQUIRED_BYTES_FOR_ENCODING       27
#define asn1SccCellState_REQUIRED_BITS_FOR_ENCODING        211

flag asn1SccCellState_Encode(const asn1SccCellState* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_CELLSTATE		38  /**/
#define ERR_UPER_DECODE_CELLSTATE_ELEVATION		18  /**/
#define ERR_UPER_DECODE_CELLSTATE_WATERVOLUME		23  /**/
#define ERR_UPER_DECODE_CELLSTATE_SURFACETYPE_2		33  /**/
flag asn1SccCellState_Decode(asn1SccCellState* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccCellState_REQUIRED_BYTES_FOR_ACN_ENCODING       27
#define asn1SccCellState_REQUIRED_BITS_FOR_ACN_ENCODING        211

#define ERR_ACN_ENCODE_CELLSTATE		39  /**/
#define ERR_ACN_ENCODE_CELLSTATE_ELEVATION		19  /**/
#define ERR_ACN_ENCODE_CELLSTATE_WATERVOLUME		24  /**/
#define ERR_ACN_ENCODE_CELLSTATE_SURFACETYPE_2		34  /**/

flag asn1SccCellState_ACN_Encode(const asn1SccCellState* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_CELLSTATE		40  /**/
#define ERR_ACN_DECODE_CELLSTATE_ELEVATION		20  /**/
#define ERR_ACN_DECODE_CELLSTATE_WATERVOLUME		25  /**/
#define ERR_ACN_DECODE_CELLSTATE_SURFACETYPE_2		35  /**/
flag asn1SccCellState_ACN_Decode(asn1SccCellState* pVal, BitStream* pBitStrm, int* pErrCode);


typedef struct {
    int nCount;
    asn1SccCellState arr[1048576];
} asn1SccGridVector;

flag asn1SccGridVector_Equal(const asn1SccGridVector* pVal1, const asn1SccGridVector* pVal2);

#define ERR_GRIDVECTOR		46  /*(SIZE(1 .. 1048576))*/
#define ERR_GRIDVECTOR_ELM		41  /**/
flag asn1SccGridVector_IsConstraintValid(const asn1SccGridVector* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccGridVector asn1SccGridVector_constant;
#else
#define asn1SccGridVector_constant {.nCount = 1, .arr  = {[0 ... 1048576-1] = asn1SccCellState_constant }}
#endif

void asn1SccGridVector_Initialize(asn1SccGridVector* pVal);

#define ERR_UPER_ENCODE_GRIDVECTOR		47  /**/
#define ERR_UPER_ENCODE_GRIDVECTOR_ELM		42  /**/
#define asn1SccGridVector_REQUIRED_BYTES_FOR_ENCODING       27656211
#define asn1SccGridVector_REQUIRED_BITS_FOR_ENCODING        221249688

flag asn1SccGridVector_Encode(const asn1SccGridVector* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_GRIDVECTOR		48  /**/
#define ERR_UPER_DECODE_GRIDVECTOR_ELM		43  /**/
flag asn1SccGridVector_Decode(asn1SccGridVector* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccGridVector_REQUIRED_BYTES_FOR_ACN_ENCODING       27656195
#define asn1SccGridVector_REQUIRED_BITS_FOR_ACN_ENCODING        221249556

#define ERR_ACN_ENCODE_GRIDVECTOR		49  /**/
#define ERR_ACN_ENCODE_GRIDVECTOR_ELM		44  /**/

flag asn1SccGridVector_ACN_Encode(const asn1SccGridVector* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_GRIDVECTOR		50  /**/
#define ERR_ACN_DECODE_GRIDVECTOR_ELM		45  /**/
flag asn1SccGridVector_ACN_Decode(asn1SccGridVector* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- asn1SccGrid --------------------------------------------*/
typedef asn1SccUint asn1SccGrid_width;

typedef asn1SccUint asn1SccGrid_height;

typedef struct {
    asn1SccGrid_width width;
    asn1SccGrid_height height;
    asn1SccGridVector cells;

} asn1SccGrid;

flag asn1SccGrid_width_Equal(const asn1SccGrid_width* pVal1, const asn1SccGrid_width* pVal2);

flag asn1SccGrid_height_Equal(const asn1SccGrid_height* pVal1, const asn1SccGrid_height* pVal2);

flag asn1SccGrid_Equal(const asn1SccGrid* pVal1, const asn1SccGrid* pVal2);

#define ERR_GRID_WIDTH		51  /*(1 .. 1024)*/
flag asn1SccGrid_width_IsConstraintValid(const asn1SccGrid_width* pVal, int* pErrCode);

#define ERR_GRID_HEIGHT		56  /*(1 .. 1024)*/
flag asn1SccGrid_height_IsConstraintValid(const asn1SccGrid_height* pVal, int* pErrCode);

#define ERR_GRID		66  /**/
#define ERR_GRID_CELLS		61  /**/
flag asn1SccGrid_IsConstraintValid(const asn1SccGrid* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccGrid_width asn1SccGrid_width_constant;
#else
#define asn1SccGrid_width_constant 1UL
#endif
#ifdef __cplusplus
extern const asn1SccGrid_height asn1SccGrid_height_constant;
#else
#define asn1SccGrid_height_constant 1UL
#endif
#ifdef __cplusplus
extern const asn1SccGrid asn1SccGrid_constant;
#else
#define asn1SccGrid_constant {.width = 1UL, .height = 1UL, .cells = asn1SccGridVector_constant}
#endif

void asn1SccGrid_Initialize(asn1SccGrid* pVal);

#define ERR_UPER_ENCODE_GRID		67  /**/
#define ERR_UPER_ENCODE_GRID_WIDTH		52  /**/
#define ERR_UPER_ENCODE_GRID_HEIGHT		57  /**/
#define ERR_UPER_ENCODE_GRID_CELLS		62  /**/
#define asn1SccGrid_REQUIRED_BYTES_FOR_ENCODING       27656214
#define asn1SccGrid_REQUIRED_BITS_FOR_ENCODING        221249708

flag asn1SccGrid_Encode(const asn1SccGrid* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_GRID		68  /**/
#define ERR_UPER_DECODE_GRID_WIDTH		53  /**/
#define ERR_UPER_DECODE_GRID_HEIGHT		58  /**/
#define ERR_UPER_DECODE_GRID_CELLS		63  /**/
flag asn1SccGrid_Decode(asn1SccGrid* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccGrid_REQUIRED_BYTES_FOR_ACN_ENCODING       27656197
#define asn1SccGrid_REQUIRED_BITS_FOR_ACN_ENCODING        221249576

#define ERR_ACN_ENCODE_GRID		69  /**/
#define ERR_ACN_ENCODE_GRID_WIDTH		54  /**/
#define ERR_ACN_ENCODE_GRID_HEIGHT		59  /**/
#define ERR_ACN_ENCODE_GRID_CELLS		64  /**/

flag asn1SccGrid_ACN_Encode(const asn1SccGrid* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_GRID		70  /**/
#define ERR_ACN_DECODE_GRID_WIDTH		55  /**/
#define ERR_ACN_DECODE_GRID_HEIGHT		60  /**/
#define ERR_ACN_DECODE_GRID_CELLS		65  /**/
flag asn1SccGrid_ACN_Decode(asn1SccGrid* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1Real asn1SccCoefficient;


flag asn1SccCoefficient_Equal(const asn1SccCoefficient* pVal1, const asn1SccCoefficient* pVal2);

#define ERR_COEFFICIENT		71  /*(0.0 .. 1.0)*/
flag asn1SccCoefficient_IsConstraintValid(const asn1SccCoefficient* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccCoefficient asn1SccCoefficient_constant;
#else
#define asn1SccCoefficient_constant 0.0000000000000000000E+000
#endif

void asn1SccCoefficient_Initialize(asn1SccCoefficient* pVal);

#define ERR_UPER_ENCODE_COEFFICIENT		72  /**/
#define asn1SccCoefficient_REQUIRED_BYTES_FOR_ENCODING       13
#define asn1SccCoefficient_REQUIRED_BITS_FOR_ENCODING        104

flag asn1SccCoefficient_Encode(const asn1SccCoefficient* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_COEFFICIENT		73  /**/
flag asn1SccCoefficient_Decode(asn1SccCoefficient* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccCoefficient_REQUIRED_BYTES_FOR_ACN_ENCODING       13
#define asn1SccCoefficient_REQUIRED_BITS_FOR_ACN_ENCODING        104

#define ERR_ACN_ENCODE_COEFFICIENT		74  /**/

flag asn1SccCoefficient_ACN_Encode(const asn1SccCoefficient* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_COEFFICIENT		75  /**/
flag asn1SccCoefficient_ACN_Decode(asn1SccCoefficient* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1Real asn1SccDuration;


flag asn1SccDuration_Equal(const asn1SccDuration* pVal1, const asn1SccDuration* pVal2);

#define ERR_DURATION		76  /*(0.0000001 .. 1000000.0)*/
flag asn1SccDuration_IsConstraintValid(const asn1SccDuration* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccDuration asn1SccDuration_constant;
#else
#define asn1SccDuration_constant 9.9999999999999995475E-008
#endif

void asn1SccDuration_Initialize(asn1SccDuration* pVal);

#define ERR_UPER_ENCODE_DURATION		77  /**/
#define asn1SccDuration_REQUIRED_BYTES_FOR_ENCODING       13
#define asn1SccDuration_REQUIRED_BITS_FOR_ENCODING        104

flag asn1SccDuration_Encode(const asn1SccDuration* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_DURATION		78  /**/
flag asn1SccDuration_Decode(asn1SccDuration* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccDuration_REQUIRED_BYTES_FOR_ACN_ENCODING       13
#define asn1SccDuration_REQUIRED_BITS_FOR_ACN_ENCODING        104

#define ERR_ACN_ENCODE_DURATION		79  /**/

flag asn1SccDuration_ACN_Encode(const asn1SccDuration* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_DURATION		80  /**/
flag asn1SccDuration_ACN_Decode(asn1SccDuration* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccUint asn1SccTimeStep;


flag asn1SccTimeStep_Equal(const asn1SccTimeStep* pVal1, const asn1SccTimeStep* pVal2);

#define ERR_TIMESTEP		81  /*(0 .. 10000)*/
flag asn1SccTimeStep_IsConstraintValid(const asn1SccTimeStep* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccTimeStep asn1SccTimeStep_constant;
#else
#define asn1SccTimeStep_constant 0UL
#endif

void asn1SccTimeStep_Initialize(asn1SccTimeStep* pVal);

#define ERR_UPER_ENCODE_TIMESTEP		82  /**/
#define asn1SccTimeStep_REQUIRED_BYTES_FOR_ENCODING       2
#define asn1SccTimeStep_REQUIRED_BITS_FOR_ENCODING        14

flag asn1SccTimeStep_Encode(const asn1SccTimeStep* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_TIMESTEP		83  /**/
flag asn1SccTimeStep_Decode(asn1SccTimeStep* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccTimeStep_REQUIRED_BYTES_FOR_ACN_ENCODING       2
#define asn1SccTimeStep_REQUIRED_BITS_FOR_ACN_ENCODING        14

#define ERR_ACN_ENCODE_TIMESTEP		84  /**/

flag asn1SccTimeStep_ACN_Encode(const asn1SccTimeStep* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_TIMESTEP		85  /**/
flag asn1SccTimeStep_ACN_Decode(asn1SccTimeStep* pVal, BitStream* pBitStrm, int* pErrCode);
typedef char asn1SccFilePath[256];

flag asn1SccFilePath_Equal(const asn1SccFilePath pVal1, const asn1SccFilePath pVal2);

#define ERR_FILEPATH		86  /*(SIZE(1..255))*/
flag asn1SccFilePath_IsConstraintValid(const asn1SccFilePath pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccFilePath asn1SccFilePath_constant;
#else
#define asn1SccFilePath_constant { [0 ... 255] = 0x0 }
#endif

void asn1SccFilePath_Initialize(asn1SccFilePath pVal);

#define ERR_UPER_ENCODE_FILEPATH		87  /**/
#define asn1SccFilePath_REQUIRED_BYTES_FOR_ENCODING       225
#define asn1SccFilePath_REQUIRED_BITS_FOR_ENCODING        1793

flag asn1SccFilePath_Encode(const asn1SccFilePath pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_FILEPATH		88  /**/
flag asn1SccFilePath_Decode(asn1SccFilePath pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccFilePath_REQUIRED_BYTES_FOR_ACN_ENCODING       225
#define asn1SccFilePath_REQUIRED_BITS_FOR_ACN_ENCODING        1793

#define ERR_ACN_ENCODE_FILEPATH		89  /**/

flag asn1SccFilePath_ACN_Encode(const asn1SccFilePath pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_FILEPATH		90  /**/
flag asn1SccFilePath_ACN_Decode(asn1SccFilePath pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccUint asn1SccCellIndex;


flag asn1SccCellIndex_Equal(const asn1SccCellIndex* pVal1, const asn1SccCellIndex* pVal2);

#define ERR_CELLINDEX		91  /*(0 .. 1048575)*/
flag asn1SccCellIndex_IsConstraintValid(const asn1SccCellIndex* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccCellIndex asn1SccCellIndex_constant;
#else
#define asn1SccCellIndex_constant 0UL
#endif

void asn1SccCellIndex_Initialize(asn1SccCellIndex* pVal);

#define ERR_UPER_ENCODE_CELLINDEX		92  /**/
#define asn1SccCellIndex_REQUIRED_BYTES_FOR_ENCODING       3
#define asn1SccCellIndex_REQUIRED_BITS_FOR_ENCODING        20

flag asn1SccCellIndex_Encode(const asn1SccCellIndex* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_CELLINDEX		93  /**/
flag asn1SccCellIndex_Decode(asn1SccCellIndex* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccCellIndex_REQUIRED_BYTES_FOR_ACN_ENCODING       3
#define asn1SccCellIndex_REQUIRED_BITS_FOR_ACN_ENCODING        20

#define ERR_ACN_ENCODE_CELLINDEX		94  /**/

flag asn1SccCellIndex_ACN_Encode(const asn1SccCellIndex* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_CELLINDEX		95  /**/
flag asn1SccCellIndex_ACN_Decode(asn1SccCellIndex* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- asn1SccOutflow --------------------------------------------*/
typedef struct {
    asn1Real volume;
    asn1SccCellIndex neighbor;

} asn1SccOutflow;

flag asn1SccOutflow_Equal(const asn1SccOutflow* pVal1, const asn1SccOutflow* pVal2);

#define ERR_OUTFLOW		111  /**/
#define ERR_OUTFLOW_VOLUME		96  /*(0.0 .. 1000.0)*/
#define ERR_OUTFLOW_NEIGHBOR_2		106  /**/
flag asn1SccOutflow_IsConstraintValid(const asn1SccOutflow* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccOutflow asn1SccOutflow_constant;
#else
#define asn1SccOutflow_constant {.volume = 0.0000000000000000000E+000, .neighbor = 0UL}
#endif

void asn1SccOutflow_Initialize(asn1SccOutflow* pVal);

#define ERR_UPER_ENCODE_OUTFLOW		112  /**/
#define ERR_UPER_ENCODE_OUTFLOW_VOLUME		97  /**/
#define ERR_UPER_ENCODE_OUTFLOW_NEIGHBOR_2		107  /**/
#define asn1SccOutflow_REQUIRED_BYTES_FOR_ENCODING       16
#define asn1SccOutflow_REQUIRED_BITS_FOR_ENCODING        124

flag asn1SccOutflow_Encode(const asn1SccOutflow* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_OUTFLOW		113  /**/
#define ERR_UPER_DECODE_OUTFLOW_VOLUME		98  /**/
#define ERR_UPER_DECODE_OUTFLOW_NEIGHBOR_2		108  /**/
flag asn1SccOutflow_Decode(asn1SccOutflow* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccOutflow_REQUIRED_BYTES_FOR_ACN_ENCODING       16
#define asn1SccOutflow_REQUIRED_BITS_FOR_ACN_ENCODING        124

#define ERR_ACN_ENCODE_OUTFLOW		114  /**/
#define ERR_ACN_ENCODE_OUTFLOW_VOLUME		99  /**/
#define ERR_ACN_ENCODE_OUTFLOW_NEIGHBOR_2		109  /**/

flag asn1SccOutflow_ACN_Encode(const asn1SccOutflow* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_OUTFLOW		115  /**/
#define ERR_ACN_DECODE_OUTFLOW_VOLUME		100  /**/
#define ERR_ACN_DECODE_OUTFLOW_NEIGHBOR_2		110  /**/
flag asn1SccOutflow_ACN_Decode(asn1SccOutflow* pVal, BitStream* pBitStrm, int* pErrCode);


typedef struct {
    int nCount;
    asn1SccOutflow arr[9];
} asn1SccOutflowList;

flag asn1SccOutflowList_Equal(const asn1SccOutflowList* pVal1, const asn1SccOutflowList* pVal2);

#define ERR_OUTFLOWLIST		121  /*(SIZE(0 .. 9))*/
#define ERR_OUTFLOWLIST_ELM		116  /**/
flag asn1SccOutflowList_IsConstraintValid(const asn1SccOutflowList* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccOutflowList asn1SccOutflowList_constant;
#else
#define asn1SccOutflowList_constant {.nCount = 0, .arr  = {[0 ... 9-1] = asn1SccOutflow_constant }}
#endif

void asn1SccOutflowList_Initialize(asn1SccOutflowList* pVal);

#define ERR_UPER_ENCODE_OUTFLOWLIST		122  /**/
#define ERR_UPER_ENCODE_OUTFLOWLIST_ELM		117  /**/
#define asn1SccOutflowList_REQUIRED_BYTES_FOR_ENCODING       140
#define asn1SccOutflowList_REQUIRED_BITS_FOR_ENCODING        1120

flag asn1SccOutflowList_Encode(const asn1SccOutflowList* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_OUTFLOWLIST		123  /**/
#define ERR_UPER_DECODE_OUTFLOWLIST_ELM		118  /**/
flag asn1SccOutflowList_Decode(asn1SccOutflowList* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccOutflowList_REQUIRED_BYTES_FOR_ACN_ENCODING       140
#define asn1SccOutflowList_REQUIRED_BITS_FOR_ACN_ENCODING        1120

#define ERR_ACN_ENCODE_OUTFLOWLIST		124  /**/
#define ERR_ACN_ENCODE_OUTFLOWLIST_ELM		119  /**/

flag asn1SccOutflowList_ACN_Encode(const asn1SccOutflowList* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_OUTFLOWLIST		125  /**/
#define ERR_ACN_DECODE_OUTFLOWLIST_ELM		120  /**/
flag asn1SccOutflowList_ACN_Decode(asn1SccOutflowList* pVal, BitStream* pBitStrm, int* pErrCode);


typedef struct {
    int nCount;
    asn1SccCellIndex arr[9];
} asn1SccMooreNeighborList;

flag asn1SccMooreNeighborList_Equal(const asn1SccMooreNeighborList* pVal1, const asn1SccMooreNeighborList* pVal2);

#define ERR_MOORENEIGHBORLIST		136  /*(SIZE(0 .. 9))*/
#define ERR_MOORENEIGHBORLIST_ELM_2		131  /**/
flag asn1SccMooreNeighborList_IsConstraintValid(const asn1SccMooreNeighborList* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccMooreNeighborList asn1SccMooreNeighborList_constant;
#else
#define asn1SccMooreNeighborList_constant {.nCount = 0, .arr  = {[0 ... 9-1] = 0UL }}
#endif

void asn1SccMooreNeighborList_Initialize(asn1SccMooreNeighborList* pVal);

#define ERR_UPER_ENCODE_MOORENEIGHBORLIST		137  /**/
#define ERR_UPER_ENCODE_MOORENEIGHBORLIST_ELM_2		132  /**/
#define asn1SccMooreNeighborList_REQUIRED_BYTES_FOR_ENCODING       23
#define asn1SccMooreNeighborList_REQUIRED_BITS_FOR_ENCODING        184

flag asn1SccMooreNeighborList_Encode(const asn1SccMooreNeighborList* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_MOORENEIGHBORLIST		138  /**/
#define ERR_UPER_DECODE_MOORENEIGHBORLIST_ELM_2		133  /**/
flag asn1SccMooreNeighborList_Decode(asn1SccMooreNeighborList* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccMooreNeighborList_REQUIRED_BYTES_FOR_ACN_ENCODING       23
#define asn1SccMooreNeighborList_REQUIRED_BITS_FOR_ACN_ENCODING        184

#define ERR_ACN_ENCODE_MOORENEIGHBORLIST		139  /**/
#define ERR_ACN_ENCODE_MOORENEIGHBORLIST_ELM_2		134  /**/

flag asn1SccMooreNeighborList_ACN_Encode(const asn1SccMooreNeighborList* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_MOORENEIGHBORLIST		140  /**/
#define ERR_ACN_DECODE_MOORENEIGHBORLIST_ELM_2		135  /**/
flag asn1SccMooreNeighborList_ACN_Decode(asn1SccMooreNeighborList* pVal, BitStream* pBitStrm, int* pErrCode);


typedef struct {
    int nCount;
    asn1SccMooreNeighborList arr[1048576];
} asn1SccGridCellNeighborList;

flag asn1SccGridCellNeighborList_Equal(const asn1SccGridCellNeighborList* pVal1, const asn1SccGridCellNeighborList* pVal2);

#define ERR_GRIDCELLNEIGHBORLIST		146  /*(SIZE(0 .. 1048576))*/
#define ERR_GRIDCELLNEIGHBORLIST_ELM		141  /**/
flag asn1SccGridCellNeighborList_IsConstraintValid(const asn1SccGridCellNeighborList* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccGridCellNeighborList asn1SccGridCellNeighborList_constant;
#else
#define asn1SccGridCellNeighborList_constant {.nCount = 0, .arr  = {[0 ... 1048576-1] = asn1SccMooreNeighborList_constant }}
#endif

void asn1SccGridCellNeighborList_Initialize(asn1SccGridCellNeighborList* pVal);

#define ERR_UPER_ENCODE_GRIDCELLNEIGHBORLIST		147  /**/
#define ERR_UPER_ENCODE_GRIDCELLNEIGHBORLIST_ELM		142  /**/
#define asn1SccGridCellNeighborList_REQUIRED_BYTES_FOR_ENCODING       24117267
#define asn1SccGridCellNeighborList_REQUIRED_BITS_FOR_ENCODING        192938136

flag asn1SccGridCellNeighborList_Encode(const asn1SccGridCellNeighborList* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_GRIDCELLNEIGHBORLIST		148  /**/
#define ERR_UPER_DECODE_GRIDCELLNEIGHBORLIST_ELM		143  /**/
flag asn1SccGridCellNeighborList_Decode(asn1SccGridCellNeighborList* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccGridCellNeighborList_REQUIRED_BYTES_FOR_ACN_ENCODING       24117251
#define asn1SccGridCellNeighborList_REQUIRED_BITS_FOR_ACN_ENCODING        192938005

#define ERR_ACN_ENCODE_GRIDCELLNEIGHBORLIST		149  /**/
#define ERR_ACN_ENCODE_GRIDCELLNEIGHBORLIST_ELM		144  /**/

flag asn1SccGridCellNeighborList_ACN_Encode(const asn1SccGridCellNeighborList* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_GRIDCELLNEIGHBORLIST		150  /**/
#define ERR_ACN_DECODE_GRIDCELLNEIGHBORLIST_ELM		145  /**/
flag asn1SccGridCellNeighborList_ACN_Decode(asn1SccGridCellNeighborList* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- asn1SccWaterIncrementEvent --------------------------------------------*/
typedef struct {
    asn1SccCellIndex targetCell;

} asn1SccWaterIncrementEvent;

flag asn1SccWaterIncrementEvent_Equal(const asn1SccWaterIncrementEvent* pVal1, const asn1SccWaterIncrementEvent* pVal2);

#define ERR_WATERINCREMENTEVENT		161  /**/
#define ERR_WATERINCREMENTEVENT_TARGETCELL_2		156  /**/
flag asn1SccWaterIncrementEvent_IsConstraintValid(const asn1SccWaterIncrementEvent* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccWaterIncrementEvent asn1SccWaterIncrementEvent_constant;
#else
#define asn1SccWaterIncrementEvent_constant {.targetCell = 0UL}
#endif

void asn1SccWaterIncrementEvent_Initialize(asn1SccWaterIncrementEvent* pVal);

#define ERR_UPER_ENCODE_WATERINCREMENTEVENT		162  /**/
#define ERR_UPER_ENCODE_WATERINCREMENTEVENT_TARGETCELL_2		157  /**/
#define asn1SccWaterIncrementEvent_REQUIRED_BYTES_FOR_ENCODING       3
#define asn1SccWaterIncrementEvent_REQUIRED_BITS_FOR_ENCODING        20

flag asn1SccWaterIncrementEvent_Encode(const asn1SccWaterIncrementEvent* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_WATERINCREMENTEVENT		163  /**/
#define ERR_UPER_DECODE_WATERINCREMENTEVENT_TARGETCELL_2		158  /**/
flag asn1SccWaterIncrementEvent_Decode(asn1SccWaterIncrementEvent* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccWaterIncrementEvent_REQUIRED_BYTES_FOR_ACN_ENCODING       3
#define asn1SccWaterIncrementEvent_REQUIRED_BITS_FOR_ACN_ENCODING        20

#define ERR_ACN_ENCODE_WATERINCREMENTEVENT		164  /**/
#define ERR_ACN_ENCODE_WATERINCREMENTEVENT_TARGETCELL_2		159  /**/

flag asn1SccWaterIncrementEvent_ACN_Encode(const asn1SccWaterIncrementEvent* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_WATERINCREMENTEVENT		165  /**/
#define ERR_ACN_DECODE_WATERINCREMENTEVENT_TARGETCELL_2		160  /**/
flag asn1SccWaterIncrementEvent_ACN_Decode(asn1SccWaterIncrementEvent* pVal, BitStream* pBitStrm, int* pErrCode);


typedef struct {
    int nCount;
    asn1SccWaterIncrementEvent arr[1048576];
} asn1SccWaterIncrementEventList;

flag asn1SccWaterIncrementEventList_Equal(const asn1SccWaterIncrementEventList* pVal1, const asn1SccWaterIncrementEventList* pVal2);

#define ERR_WATERINCREMENTEVENTLIST		171  /*(SIZE(0 .. 1048576))*/
#define ERR_WATERINCREMENTEVENTLIST_ELM		166  /**/
flag asn1SccWaterIncrementEventList_IsConstraintValid(const asn1SccWaterIncrementEventList* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccWaterIncrementEventList asn1SccWaterIncrementEventList_constant;
#else
#define asn1SccWaterIncrementEventList_constant {.nCount = 0, .arr  = {[0 ... 1048576-1] = asn1SccWaterIncrementEvent_constant }}
#endif

void asn1SccWaterIncrementEventList_Initialize(asn1SccWaterIncrementEventList* pVal);

#define ERR_UPER_ENCODE_WATERINCREMENTEVENTLIST		172  /**/
#define ERR_UPER_ENCODE_WATERINCREMENTEVENTLIST_ELM		167  /**/
#define asn1SccWaterIncrementEventList_REQUIRED_BYTES_FOR_ENCODING       2621459
#define asn1SccWaterIncrementEventList_REQUIRED_BITS_FOR_ENCODING        20971672

flag asn1SccWaterIncrementEventList_Encode(const asn1SccWaterIncrementEventList* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_WATERINCREMENTEVENTLIST		173  /**/
#define ERR_UPER_DECODE_WATERINCREMENTEVENTLIST_ELM		168  /**/
flag asn1SccWaterIncrementEventList_Decode(asn1SccWaterIncrementEventList* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccWaterIncrementEventList_REQUIRED_BYTES_FOR_ACN_ENCODING       2621443
#define asn1SccWaterIncrementEventList_REQUIRED_BITS_FOR_ACN_ENCODING        20971541

#define ERR_ACN_ENCODE_WATERINCREMENTEVENTLIST		174  /**/
#define ERR_ACN_ENCODE_WATERINCREMENTEVENTLIST_ELM		169  /**/

flag asn1SccWaterIncrementEventList_ACN_Encode(const asn1SccWaterIncrementEventList* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_WATERINCREMENTEVENTLIST		175  /**/
#define ERR_ACN_DECODE_WATERINCREMENTEVENTLIST_ELM		170  /**/
flag asn1SccWaterIncrementEventList_ACN_Decode(asn1SccWaterIncrementEventList* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- asn1SccGridModification --------------------------------------------*/
typedef struct {
    asn1SccCellIndex targetCell;
    asn1Real delta;

} asn1SccGridModification;

flag asn1SccGridModification_Equal(const asn1SccGridModification* pVal1, const asn1SccGridModification* pVal2);

#define ERR_GRIDMODIFICATION		191  /**/
#define ERR_GRIDMODIFICATION_TARGETCELL_2		181  /**/
#define ERR_GRIDMODIFICATION_DELTA		186  /*(-1000.0 .. 1000.0)*/
flag asn1SccGridModification_IsConstraintValid(const asn1SccGridModification* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccGridModification asn1SccGridModification_constant;
#else
#define asn1SccGridModification_constant {.targetCell = 0UL, .delta = 0.0000000000000000000E+000}
#endif

void asn1SccGridModification_Initialize(asn1SccGridModification* pVal);

#define ERR_UPER_ENCODE_GRIDMODIFICATION		192  /**/
#define ERR_UPER_ENCODE_GRIDMODIFICATION_TARGETCELL_2		182  /**/
#define ERR_UPER_ENCODE_GRIDMODIFICATION_DELTA		187  /**/
#define asn1SccGridModification_REQUIRED_BYTES_FOR_ENCODING       16
#define asn1SccGridModification_REQUIRED_BITS_FOR_ENCODING        124

flag asn1SccGridModification_Encode(const asn1SccGridModification* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_GRIDMODIFICATION		193  /**/
#define ERR_UPER_DECODE_GRIDMODIFICATION_TARGETCELL_2		183  /**/
#define ERR_UPER_DECODE_GRIDMODIFICATION_DELTA		188  /**/
flag asn1SccGridModification_Decode(asn1SccGridModification* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccGridModification_REQUIRED_BYTES_FOR_ACN_ENCODING       16
#define asn1SccGridModification_REQUIRED_BITS_FOR_ACN_ENCODING        124

#define ERR_ACN_ENCODE_GRIDMODIFICATION		194  /**/
#define ERR_ACN_ENCODE_GRIDMODIFICATION_TARGETCELL_2		184  /**/
#define ERR_ACN_ENCODE_GRIDMODIFICATION_DELTA		189  /**/

flag asn1SccGridModification_ACN_Encode(const asn1SccGridModification* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_GRIDMODIFICATION		195  /**/
#define ERR_ACN_DECODE_GRIDMODIFICATION_TARGETCELL_2		185  /**/
#define ERR_ACN_DECODE_GRIDMODIFICATION_DELTA		190  /**/
flag asn1SccGridModification_ACN_Decode(asn1SccGridModification* pVal, BitStream* pBitStrm, int* pErrCode);


typedef struct {
    int nCount;
    asn1SccGridModification arr[4294967295LL];
} asn1SccGridModificationList;

flag asn1SccGridModificationList_Equal(const asn1SccGridModificationList* pVal1, const asn1SccGridModificationList* pVal2);

#define ERR_GRIDMODIFICATIONLIST		201  /*(SIZE(0 .. 4294967295))*/
#define ERR_GRIDMODIFICATIONLIST_ELM		196  /**/
flag asn1SccGridModificationList_IsConstraintValid(const asn1SccGridModificationList* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccGridModificationList asn1SccGridModificationList_constant;
#else
#define asn1SccGridModificationList_constant {.nCount = 0, .arr  = {[0 ... 4294967295LL-1] = asn1SccGridModification_constant }}
#endif

void asn1SccGridModificationList_Initialize(asn1SccGridModificationList* pVal);

#define ERR_UPER_ENCODE_GRIDMODIFICATIONLIST		202  /**/
#define ERR_UPER_ENCODE_GRIDMODIFICATIONLIST_ELM		197  /**/
#define asn1SccGridModificationList_REQUIRED_BYTES_FOR_ENCODING       66572058611LL
#define asn1SccGridModificationList_REQUIRED_BITS_FOR_ENCODING        532576468884LL

flag asn1SccGridModificationList_Encode(const asn1SccGridModificationList* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_GRIDMODIFICATIONLIST		203  /**/
#define ERR_UPER_DECODE_GRIDMODIFICATIONLIST_ELM		198  /**/
flag asn1SccGridModificationList_Decode(asn1SccGridModificationList* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccGridModificationList_REQUIRED_BYTES_FOR_ACN_ENCODING       66571993077LL
#define asn1SccGridModificationList_REQUIRED_BITS_FOR_ACN_ENCODING        532575944612LL

#define ERR_ACN_ENCODE_GRIDMODIFICATIONLIST		204  /**/
#define ERR_ACN_ENCODE_GRIDMODIFICATIONLIST_ELM		199  /**/

flag asn1SccGridModificationList_ACN_Encode(const asn1SccGridModificationList* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_GRIDMODIFICATIONLIST		205  /**/
#define ERR_ACN_DECODE_GRIDMODIFICATIONLIST_ELM		200  /**/
flag asn1SccGridModificationList_ACN_Decode(asn1SccGridModificationList* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1Real asn1SccWaterVolume;


flag asn1SccWaterVolume_Equal(const asn1SccWaterVolume* pVal1, const asn1SccWaterVolume* pVal2);

#define ERR_WATERVOLUME		206  /*(0.0 .. 1000.0)*/
flag asn1SccWaterVolume_IsConstraintValid(const asn1SccWaterVolume* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccWaterVolume asn1SccWaterVolume_constant;
#else
#define asn1SccWaterVolume_constant 0.0000000000000000000E+000
#endif

void asn1SccWaterVolume_Initialize(asn1SccWaterVolume* pVal);

#define ERR_UPER_ENCODE_WATERVOLUME		207  /**/
#define asn1SccWaterVolume_REQUIRED_BYTES_FOR_ENCODING       13
#define asn1SccWaterVolume_REQUIRED_BITS_FOR_ENCODING        104

flag asn1SccWaterVolume_Encode(const asn1SccWaterVolume* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_WATERVOLUME		208  /**/
flag asn1SccWaterVolume_Decode(asn1SccWaterVolume* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccWaterVolume_REQUIRED_BYTES_FOR_ACN_ENCODING       13
#define asn1SccWaterVolume_REQUIRED_BITS_FOR_ACN_ENCODING        104

#define ERR_ACN_ENCODE_WATERVOLUME		209  /**/

flag asn1SccWaterVolume_ACN_Encode(const asn1SccWaterVolume* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_WATERVOLUME		210  /**/
flag asn1SccWaterVolume_ACN_Decode(asn1SccWaterVolume* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1Real asn1SccTotalOutflow;


flag asn1SccTotalOutflow_Equal(const asn1SccTotalOutflow* pVal1, const asn1SccTotalOutflow* pVal2);

#define ERR_TOTALOUTFLOW		211  /*(0.0 .. 8000.0)*/
flag asn1SccTotalOutflow_IsConstraintValid(const asn1SccTotalOutflow* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccTotalOutflow asn1SccTotalOutflow_constant;
#else
#define asn1SccTotalOutflow_constant 0.0000000000000000000E+000
#endif

void asn1SccTotalOutflow_Initialize(asn1SccTotalOutflow* pVal);

#define ERR_UPER_ENCODE_TOTALOUTFLOW		212  /**/
#define asn1SccTotalOutflow_REQUIRED_BYTES_FOR_ENCODING       13
#define asn1SccTotalOutflow_REQUIRED_BITS_FOR_ENCODING        104

flag asn1SccTotalOutflow_Encode(const asn1SccTotalOutflow* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_TOTALOUTFLOW		213  /**/
flag asn1SccTotalOutflow_Decode(asn1SccTotalOutflow* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccTotalOutflow_REQUIRED_BYTES_FOR_ACN_ENCODING       13
#define asn1SccTotalOutflow_REQUIRED_BITS_FOR_ACN_ENCODING        104

#define ERR_ACN_ENCODE_TOTALOUTFLOW		214  /**/

flag asn1SccTotalOutflow_ACN_Encode(const asn1SccTotalOutflow* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_TOTALOUTFLOW		215  /**/
flag asn1SccTotalOutflow_ACN_Decode(asn1SccTotalOutflow* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccUint asn1SccMooreNeighborIndex;


flag asn1SccMooreNeighborIndex_Equal(const asn1SccMooreNeighborIndex* pVal1, const asn1SccMooreNeighborIndex* pVal2);

#define ERR_MOORENEIGHBORINDEX		216  /*(0 .. 8)*/
flag asn1SccMooreNeighborIndex_IsConstraintValid(const asn1SccMooreNeighborIndex* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccMooreNeighborIndex asn1SccMooreNeighborIndex_constant;
#else
#define asn1SccMooreNeighborIndex_constant 0UL
#endif

void asn1SccMooreNeighborIndex_Initialize(asn1SccMooreNeighborIndex* pVal);

#define ERR_UPER_ENCODE_MOORENEIGHBORINDEX		217  /**/
#define asn1SccMooreNeighborIndex_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccMooreNeighborIndex_REQUIRED_BITS_FOR_ENCODING        4

flag asn1SccMooreNeighborIndex_Encode(const asn1SccMooreNeighborIndex* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_MOORENEIGHBORINDEX		218  /**/
flag asn1SccMooreNeighborIndex_Decode(asn1SccMooreNeighborIndex* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccMooreNeighborIndex_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccMooreNeighborIndex_REQUIRED_BITS_FOR_ACN_ENCODING        4

#define ERR_ACN_ENCODE_MOORENEIGHBORINDEX		219  /**/

flag asn1SccMooreNeighborIndex_ACN_Encode(const asn1SccMooreNeighborIndex* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_MOORENEIGHBORINDEX		220  /**/
flag asn1SccMooreNeighborIndex_ACN_Decode(asn1SccMooreNeighborIndex* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccSint asn1SccT_Int32;


flag asn1SccT_Int32_Equal(const asn1SccT_Int32* pVal1, const asn1SccT_Int32* pVal2);

#define ERR_T_INT32		221  /*(-2147483648 .. 2147483647)*/
flag asn1SccT_Int32_IsConstraintValid(const asn1SccT_Int32* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_Int32 asn1SccT_Int32_constant;
#else
#define asn1SccT_Int32_constant 0LL
#endif

void asn1SccT_Int32_Initialize(asn1SccT_Int32* pVal);

#define ERR_UPER_ENCODE_T_INT32		222  /**/
#define asn1SccT_Int32_REQUIRED_BYTES_FOR_ENCODING       4
#define asn1SccT_Int32_REQUIRED_BITS_FOR_ENCODING        32

flag asn1SccT_Int32_Encode(const asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_INT32		223  /**/
flag asn1SccT_Int32_Decode(asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_Int32_REQUIRED_BYTES_FOR_ACN_ENCODING       4
#define asn1SccT_Int32_REQUIRED_BITS_FOR_ACN_ENCODING        32

#define ERR_ACN_ENCODE_T_INT32		224  /**/

flag asn1SccT_Int32_ACN_Encode(const asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_INT32		225  /**/
flag asn1SccT_Int32_ACN_Decode(asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccUint asn1SccT_UInt32;


flag asn1SccT_UInt32_Equal(const asn1SccT_UInt32* pVal1, const asn1SccT_UInt32* pVal2);

#define ERR_T_UINT32		226  /*(0 .. 4294967294)*/
flag asn1SccT_UInt32_IsConstraintValid(const asn1SccT_UInt32* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_UInt32 asn1SccT_UInt32_constant;
#else
#define asn1SccT_UInt32_constant 0UL
#endif

void asn1SccT_UInt32_Initialize(asn1SccT_UInt32* pVal);

#define ERR_UPER_ENCODE_T_UINT32		227  /**/
#define asn1SccT_UInt32_REQUIRED_BYTES_FOR_ENCODING       4
#define asn1SccT_UInt32_REQUIRED_BITS_FOR_ENCODING        32

flag asn1SccT_UInt32_Encode(const asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_UINT32		228  /**/
flag asn1SccT_UInt32_Decode(asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_UInt32_REQUIRED_BYTES_FOR_ACN_ENCODING       4
#define asn1SccT_UInt32_REQUIRED_BITS_FOR_ACN_ENCODING        32

#define ERR_ACN_ENCODE_T_UINT32		229  /**/

flag asn1SccT_UInt32_ACN_Encode(const asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_UINT32		230  /**/
flag asn1SccT_UInt32_ACN_Decode(asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- asn1SccT_Runtime_Error --------------------------------------------*/

typedef enum {
    T_Runtime_Error_NONE,
    T_Runtime_Error_noerror_PRESENT,
    T_Runtime_Error_encodeerror_PRESENT,
    T_Runtime_Error_decodeerror_PRESENT
} asn1SccT_Runtime_Error_selection;

typedef union {
    asn1SccT_UInt32 noerror;
    asn1SccT_Int32 encodeerror;
    asn1SccT_Int32 decodeerror;
} asn1SccT_Runtime_Error_unchecked_union;

typedef struct {
    asn1SccT_Runtime_Error_selection kind;

    asn1SccT_Runtime_Error_unchecked_union u;
} asn1SccT_Runtime_Error;

flag asn1SccT_Runtime_Error_Equal(const asn1SccT_Runtime_Error* pVal1, const asn1SccT_Runtime_Error* pVal2);

#define ERR_T_RUNTIME_ERROR		261  /**/
#define ERR_T_RUNTIME_ERROR_NOERROR_2		236  /**/
#define ERR_T_RUNTIME_ERROR_ENCODEERROR_2		246  /**/
#define ERR_T_RUNTIME_ERROR_DECODEERROR_2		256  /**/
flag asn1SccT_Runtime_Error_IsConstraintValid(const asn1SccT_Runtime_Error* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_Runtime_Error asn1SccT_Runtime_Error_constant;
#else
#define asn1SccT_Runtime_Error_constant {.kind = T_Runtime_Error_noerror_PRESENT, .u.noerror = 0UL}
#endif

void asn1SccT_Runtime_Error_Initialize(asn1SccT_Runtime_Error* pVal);

#define ERR_UPER_ENCODE_T_RUNTIME_ERROR		262  /**/
#define ERR_UPER_ENCODE_T_RUNTIME_ERROR_NOERROR_2		237  /**/
#define ERR_UPER_ENCODE_T_RUNTIME_ERROR_ENCODEERROR_2		247  /**/
#define ERR_UPER_ENCODE_T_RUNTIME_ERROR_DECODEERROR_2		257  /**/
#define asn1SccT_Runtime_Error_REQUIRED_BYTES_FOR_ENCODING       5
#define asn1SccT_Runtime_Error_REQUIRED_BITS_FOR_ENCODING        34

flag asn1SccT_Runtime_Error_Encode(const asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_RUNTIME_ERROR		263  /**/
#define ERR_UPER_DECODE_T_RUNTIME_ERROR_NOERROR_2		238  /**/
#define ERR_UPER_DECODE_T_RUNTIME_ERROR_ENCODEERROR_2		248  /**/
#define ERR_UPER_DECODE_T_RUNTIME_ERROR_DECODEERROR_2		258  /**/
flag asn1SccT_Runtime_Error_Decode(asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_Runtime_Error_REQUIRED_BYTES_FOR_ACN_ENCODING       5
#define asn1SccT_Runtime_Error_REQUIRED_BITS_FOR_ACN_ENCODING        34

#define ERR_ACN_ENCODE_T_RUNTIME_ERROR		264  /**/
#define ERR_ACN_ENCODE_T_RUNTIME_ERROR_NOERROR_2		239  /**/
#define ERR_ACN_ENCODE_T_RUNTIME_ERROR_ENCODEERROR_2		249  /**/
#define ERR_ACN_ENCODE_T_RUNTIME_ERROR_DECODEERROR_2		259  /**/

flag asn1SccT_Runtime_Error_ACN_Encode(const asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_RUNTIME_ERROR		265  /**/
#define ERR_ACN_DECODE_T_RUNTIME_ERROR_NOERROR_2		240  /**/
#define ERR_ACN_DECODE_T_RUNTIME_ERROR_ENCODEERROR_2		250  /**/
#define ERR_ACN_DECODE_T_RUNTIME_ERROR_DECODEERROR_2		260  /**/
flag asn1SccT_Runtime_Error_ACN_Decode(asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccSint asn1SccT_Int8;


flag asn1SccT_Int8_Equal(const asn1SccT_Int8* pVal1, const asn1SccT_Int8* pVal2);

#define ERR_T_INT8		266  /*(-128 .. 127)*/
flag asn1SccT_Int8_IsConstraintValid(const asn1SccT_Int8* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_Int8 asn1SccT_Int8_constant;
#else
#define asn1SccT_Int8_constant 0LL
#endif

void asn1SccT_Int8_Initialize(asn1SccT_Int8* pVal);

#define ERR_UPER_ENCODE_T_INT8		267  /**/
#define asn1SccT_Int8_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccT_Int8_REQUIRED_BITS_FOR_ENCODING        8

flag asn1SccT_Int8_Encode(const asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_INT8		268  /**/
flag asn1SccT_Int8_Decode(asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_Int8_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccT_Int8_REQUIRED_BITS_FOR_ACN_ENCODING        8

#define ERR_ACN_ENCODE_T_INT8		269  /**/

flag asn1SccT_Int8_ACN_Encode(const asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_INT8		270  /**/
flag asn1SccT_Int8_ACN_Decode(asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccUint asn1SccT_UInt8;


flag asn1SccT_UInt8_Equal(const asn1SccT_UInt8* pVal1, const asn1SccT_UInt8* pVal2);

#define ERR_T_UINT8		271  /*(0 .. 255)*/
flag asn1SccT_UInt8_IsConstraintValid(const asn1SccT_UInt8* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_UInt8 asn1SccT_UInt8_constant;
#else
#define asn1SccT_UInt8_constant 0UL
#endif

void asn1SccT_UInt8_Initialize(asn1SccT_UInt8* pVal);

#define ERR_UPER_ENCODE_T_UINT8		272  /**/
#define asn1SccT_UInt8_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccT_UInt8_REQUIRED_BITS_FOR_ENCODING        8

flag asn1SccT_UInt8_Encode(const asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_UINT8		273  /**/
flag asn1SccT_UInt8_Decode(asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_UInt8_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccT_UInt8_REQUIRED_BITS_FOR_ACN_ENCODING        8

#define ERR_ACN_ENCODE_T_UINT8		274  /**/

flag asn1SccT_UInt8_ACN_Encode(const asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_UINT8		275  /**/
flag asn1SccT_UInt8_ACN_Decode(asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode);
typedef flag asn1SccT_Boolean;


flag asn1SccT_Boolean_Equal(const asn1SccT_Boolean* pVal1, const asn1SccT_Boolean* pVal2);

#define ERR_T_BOOLEAN		276  /**/
flag asn1SccT_Boolean_IsConstraintValid(const asn1SccT_Boolean* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_Boolean asn1SccT_Boolean_constant;
#else
#define asn1SccT_Boolean_constant FALSE
#endif

void asn1SccT_Boolean_Initialize(asn1SccT_Boolean* pVal);

#define ERR_UPER_ENCODE_T_BOOLEAN		277  /**/
#define asn1SccT_Boolean_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccT_Boolean_REQUIRED_BITS_FOR_ENCODING        1

flag asn1SccT_Boolean_Encode(const asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_BOOLEAN		278  /**/
flag asn1SccT_Boolean_Decode(asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_Boolean_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccT_Boolean_REQUIRED_BITS_FOR_ACN_ENCODING        1

#define ERR_ACN_ENCODE_T_BOOLEAN		279  /**/

flag asn1SccT_Boolean_ACN_Encode(const asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_BOOLEAN		280  /**/
flag asn1SccT_Boolean_ACN_Decode(asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- asn1SccT_Null_Record --------------------------------------------*/
typedef struct {

} asn1SccT_Null_Record;

flag asn1SccT_Null_Record_Equal(const asn1SccT_Null_Record* pVal1, const asn1SccT_Null_Record* pVal2);

#define ERR_T_NULL_RECORD		281  /**/
flag asn1SccT_Null_Record_IsConstraintValid(const asn1SccT_Null_Record* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_Null_Record asn1SccT_Null_Record_constant;
#else
#define asn1SccT_Null_Record_constant {}
#endif

void asn1SccT_Null_Record_Initialize(asn1SccT_Null_Record* pVal);

#define asn1SccT_Null_Record_REQUIRED_BYTES_FOR_ENCODING       0
#define asn1SccT_Null_Record_REQUIRED_BITS_FOR_ENCODING        0

flag asn1SccT_Null_Record_Encode(const asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

flag asn1SccT_Null_Record_Decode(asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_Null_Record_REQUIRED_BYTES_FOR_ACN_ENCODING       0
#define asn1SccT_Null_Record_REQUIRED_BITS_FOR_ACN_ENCODING        0


flag asn1SccT_Null_Record_ACN_Encode(const asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

flag asn1SccT_Null_Record_ACN_Decode(asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccUint asn1SccPID_Range;


flag asn1SccPID_Range_Equal(const asn1SccPID_Range* pVal1, const asn1SccPID_Range* pVal2);

#define ERR_PID_RANGE		286  /*(0..3)*/
flag asn1SccPID_Range_IsConstraintValid(const asn1SccPID_Range* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccPID_Range asn1SccPID_Range_constant;
#else
#define asn1SccPID_Range_constant 0UL
#endif

void asn1SccPID_Range_Initialize(asn1SccPID_Range* pVal);

#define ERR_UPER_ENCODE_PID_RANGE		287  /**/
#define asn1SccPID_Range_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccPID_Range_REQUIRED_BITS_FOR_ENCODING        2

flag asn1SccPID_Range_Encode(const asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_PID_RANGE		288  /**/
flag asn1SccPID_Range_Decode(asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccPID_Range_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccPID_Range_REQUIRED_BITS_FOR_ACN_ENCODING        2

#define ERR_ACN_ENCODE_PID_RANGE		289  /**/

flag asn1SccPID_Range_ACN_Encode(const asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_PID_RANGE		290  /**/
flag asn1SccPID_Range_ACN_Decode(asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode);
typedef enum {
    PID_core = 0,
    PID_io_gis = 1,
    PID_ui = 2,
    PID_env = 3
} asn1SccPID;

// please use the following macros to avoid breaking code.
#define asn1SccPID_core PID_core
#define asn1SccPID_io_gis PID_io_gis
#define asn1SccPID_ui PID_ui
#define asn1SccPID_env PID_env

flag asn1SccPID_Equal(const asn1SccPID* pVal1, const asn1SccPID* pVal2);

#define ERR_PID		291  /*core | io-gis | ui | env*/
flag asn1SccPID_IsConstraintValid(const asn1SccPID* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccPID asn1SccPID_constant;
#else
#define asn1SccPID_constant PID_core
#endif

void asn1SccPID_Initialize(asn1SccPID* pVal);

#define ERR_UPER_ENCODE_PID		292  /**/
#define asn1SccPID_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccPID_REQUIRED_BITS_FOR_ENCODING        2

flag asn1SccPID_Encode(const asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_PID		293  /**/
flag asn1SccPID_Decode(asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccPID_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccPID_REQUIRED_BITS_FOR_ACN_ENCODING        2

#define ERR_ACN_ENCODE_PID		294  /**/

flag asn1SccPID_ACN_Encode(const asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_PID		295  /**/
flag asn1SccPID_ACN_Decode(asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode);


/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */



#ifdef  __cplusplus
}

#endif

#endif
