#ifndef GENERATED_ASN1SCC_dataview_uniq_H
#define GENERATED_ASN1SCC_dataview_uniq_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "asn1crt_encoding.h"


#ifdef  __cplusplus
extern "C" {
#endif


typedef asn1SccUint asn1SccT_UInt32;


flag asn1SccT_UInt32_Equal(const asn1SccT_UInt32* pVal1, const asn1SccT_UInt32* pVal2);

#define ERR_T_UINT32		1  /*(0 .. 4294967294)*/
flag asn1SccT_UInt32_IsConstraintValid(const asn1SccT_UInt32* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_UInt32 asn1SccT_UInt32_constant;
#else
#define asn1SccT_UInt32_constant 0UL
#endif

void asn1SccT_UInt32_Initialize(asn1SccT_UInt32* pVal);

#define ERR_UPER_ENCODE_T_UINT32		2  /**/
#define asn1SccT_UInt32_REQUIRED_BYTES_FOR_ENCODING       4
#define asn1SccT_UInt32_REQUIRED_BITS_FOR_ENCODING        32

flag asn1SccT_UInt32_Encode(const asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_UINT32		3  /**/
flag asn1SccT_UInt32_Decode(asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_UInt32_REQUIRED_BYTES_FOR_ACN_ENCODING       4
#define asn1SccT_UInt32_REQUIRED_BITS_FOR_ACN_ENCODING        32

#define ERR_ACN_ENCODE_T_UINT32		4  /**/

flag asn1SccT_UInt32_ACN_Encode(const asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_UINT32		5  /**/
flag asn1SccT_UInt32_ACN_Decode(asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1Real asn1SccT_Float;


flag asn1SccT_Float_Equal(const asn1SccT_Float* pVal1, const asn1SccT_Float* pVal2);

#define ERR_T_FLOAT		6  /*(-2147483648.0 .. 2147483647.0)*/
flag asn1SccT_Float_IsConstraintValid(const asn1SccT_Float* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_Float asn1SccT_Float_constant;
#else
#define asn1SccT_Float_constant 0.0000000000000000000E+000
#endif

void asn1SccT_Float_Initialize(asn1SccT_Float* pVal);

#define ERR_UPER_ENCODE_T_FLOAT		7  /**/
#define asn1SccT_Float_REQUIRED_BYTES_FOR_ENCODING       13
#define asn1SccT_Float_REQUIRED_BITS_FOR_ENCODING        104

flag asn1SccT_Float_Encode(const asn1SccT_Float* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_FLOAT		8  /**/
flag asn1SccT_Float_Decode(asn1SccT_Float* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_Float_REQUIRED_BYTES_FOR_ACN_ENCODING       13
#define asn1SccT_Float_REQUIRED_BITS_FOR_ACN_ENCODING        104

#define ERR_ACN_ENCODE_T_FLOAT		9  /**/

flag asn1SccT_Float_ACN_Encode(const asn1SccT_Float* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_FLOAT		10  /**/
flag asn1SccT_Float_ACN_Decode(asn1SccT_Float* pVal, BitStream* pBitStrm, int* pErrCode);


typedef struct {
    int nCount;
    asn1SccT_Float arr[1048576];
} asn1SccLayer;

flag asn1SccLayer_Equal(const asn1SccLayer* pVal1, const asn1SccLayer* pVal2);

#define ERR_LAYER		21  /*SIZE (1 .. 1048576)*/
#define ERR_LAYER_ELM_2		16  /**/
flag asn1SccLayer_IsConstraintValid(const asn1SccLayer* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccLayer asn1SccLayer_constant;
#else
#define asn1SccLayer_constant {.nCount = 1, .arr  = {[0 ... 1048576-1] = 0.0000000000000000000E+000 }}
#endif

void asn1SccLayer_Initialize(asn1SccLayer* pVal);

#define ERR_UPER_ENCODE_LAYER		22  /**/
#define ERR_UPER_ENCODE_LAYER_ELM_2		17  /**/
#define asn1SccLayer_REQUIRED_BYTES_FOR_ENCODING       13631507
#define asn1SccLayer_REQUIRED_BITS_FOR_ENCODING        109052056

flag asn1SccLayer_Encode(const asn1SccLayer* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_LAYER		23  /**/
#define ERR_UPER_DECODE_LAYER_ELM_2		18  /**/
flag asn1SccLayer_Decode(asn1SccLayer* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccLayer_REQUIRED_BYTES_FOR_ACN_ENCODING       13631491
#define asn1SccLayer_REQUIRED_BITS_FOR_ACN_ENCODING        109051924

#define ERR_ACN_ENCODE_LAYER		24  /**/
#define ERR_ACN_ENCODE_LAYER_ELM_2		19  /**/

flag asn1SccLayer_ACN_Encode(const asn1SccLayer* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_LAYER		25  /**/
#define ERR_ACN_DECODE_LAYER_ELM_2		20  /**/
flag asn1SccLayer_ACN_Decode(asn1SccLayer* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- asn1SccCellularAutomatonState --------------------------------------------*/
typedef asn1SccUint asn1SccCellularAutomatonState_rows;

typedef asn1SccUint asn1SccCellularAutomatonState_cols;

typedef struct {
    asn1SccCellularAutomatonState_rows rows;
    asn1SccCellularAutomatonState_cols cols;
    asn1SccT_Float timestamp;
    asn1SccT_UInt32 stepIndex;
    asn1SccLayer elevation;
    asn1SccLayer waterDepth;

} asn1SccCellularAutomatonState;

flag asn1SccCellularAutomatonState_rows_Equal(const asn1SccCellularAutomatonState_rows* pVal1, const asn1SccCellularAutomatonState_rows* pVal2);

flag asn1SccCellularAutomatonState_cols_Equal(const asn1SccCellularAutomatonState_cols* pVal1, const asn1SccCellularAutomatonState_cols* pVal2);

flag asn1SccCellularAutomatonState_Equal(const asn1SccCellularAutomatonState* pVal1, const asn1SccCellularAutomatonState* pVal2);

#define ERR_CELLULARAUTOMATONSTATE_ROWS		26  /*(1 .. 1024)*/
flag asn1SccCellularAutomatonState_rows_IsConstraintValid(const asn1SccCellularAutomatonState_rows* pVal, int* pErrCode);

#define ERR_CELLULARAUTOMATONSTATE_COLS		31  /*(1 .. 1024)*/
flag asn1SccCellularAutomatonState_cols_IsConstraintValid(const asn1SccCellularAutomatonState_cols* pVal, int* pErrCode);

#define ERR_CELLULARAUTOMATONSTATE		66  /**/
#define ERR_CELLULARAUTOMATONSTATE_TIMESTAMP_2		41  /**/
#define ERR_CELLULARAUTOMATONSTATE_STEPINDEX_2		51  /**/
#define ERR_CELLULARAUTOMATONSTATE_ELEVATION		56  /**/
#define ERR_CELLULARAUTOMATONSTATE_WATERDEPTH		61  /**/
flag asn1SccCellularAutomatonState_IsConstraintValid(const asn1SccCellularAutomatonState* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccCellularAutomatonState_rows asn1SccCellularAutomatonState_rows_constant;
#else
#define asn1SccCellularAutomatonState_rows_constant 1UL
#endif
#ifdef __cplusplus
extern const asn1SccCellularAutomatonState_cols asn1SccCellularAutomatonState_cols_constant;
#else
#define asn1SccCellularAutomatonState_cols_constant 1UL
#endif
#ifdef __cplusplus
extern const asn1SccCellularAutomatonState asn1SccCellularAutomatonState_constant;
#else
#define asn1SccCellularAutomatonState_constant {.rows = 1UL, .cols = 1UL, .timestamp = 0.0000000000000000000E+000, .stepIndex = 0UL, .elevation = asn1SccLayer_constant, .waterDepth = asn1SccLayer_constant}
#endif

void asn1SccCellularAutomatonState_Initialize(asn1SccCellularAutomatonState* pVal);

#define ERR_UPER_ENCODE_CELLULARAUTOMATONSTATE		67  /**/
#define ERR_UPER_ENCODE_CELLULARAUTOMATONSTATE_ROWS		27  /**/
#define ERR_UPER_ENCODE_CELLULARAUTOMATONSTATE_COLS		32  /**/
#define ERR_UPER_ENCODE_CELLULARAUTOMATONSTATE_TIMESTAMP_2		42  /**/
#define ERR_UPER_ENCODE_CELLULARAUTOMATONSTATE_STEPINDEX_2		52  /**/
#define ERR_UPER_ENCODE_CELLULARAUTOMATONSTATE_ELEVATION		57  /**/
#define ERR_UPER_ENCODE_CELLULARAUTOMATONSTATE_WATERDEPTH		62  /**/
#define asn1SccCellularAutomatonState_REQUIRED_BYTES_FOR_ENCODING       27263034
#define asn1SccCellularAutomatonState_REQUIRED_BITS_FOR_ENCODING        218104268

flag asn1SccCellularAutomatonState_Encode(const asn1SccCellularAutomatonState* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_CELLULARAUTOMATONSTATE		68  /**/
#define ERR_UPER_DECODE_CELLULARAUTOMATONSTATE_ROWS		28  /**/
#define ERR_UPER_DECODE_CELLULARAUTOMATONSTATE_COLS		33  /**/
#define ERR_UPER_DECODE_CELLULARAUTOMATONSTATE_TIMESTAMP_2		43  /**/
#define ERR_UPER_DECODE_CELLULARAUTOMATONSTATE_STEPINDEX_2		53  /**/
#define ERR_UPER_DECODE_CELLULARAUTOMATONSTATE_ELEVATION		58  /**/
#define ERR_UPER_DECODE_CELLULARAUTOMATONSTATE_WATERDEPTH		63  /**/
flag asn1SccCellularAutomatonState_Decode(asn1SccCellularAutomatonState* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccCellularAutomatonState_REQUIRED_BYTES_FOR_ACN_ENCODING       27263001
#define asn1SccCellularAutomatonState_REQUIRED_BITS_FOR_ACN_ENCODING        218104004

#define ERR_ACN_ENCODE_CELLULARAUTOMATONSTATE		69  /**/
#define ERR_ACN_ENCODE_CELLULARAUTOMATONSTATE_ROWS		29  /**/
#define ERR_ACN_ENCODE_CELLULARAUTOMATONSTATE_COLS		34  /**/
#define ERR_ACN_ENCODE_CELLULARAUTOMATONSTATE_TIMESTAMP_2		44  /**/
#define ERR_ACN_ENCODE_CELLULARAUTOMATONSTATE_STEPINDEX_2		54  /**/
#define ERR_ACN_ENCODE_CELLULARAUTOMATONSTATE_ELEVATION		59  /**/
#define ERR_ACN_ENCODE_CELLULARAUTOMATONSTATE_WATERDEPTH		64  /**/

flag asn1SccCellularAutomatonState_ACN_Encode(const asn1SccCellularAutomatonState* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_CELLULARAUTOMATONSTATE		70  /**/
#define ERR_ACN_DECODE_CELLULARAUTOMATONSTATE_ROWS		30  /**/
#define ERR_ACN_DECODE_CELLULARAUTOMATONSTATE_COLS		35  /**/
#define ERR_ACN_DECODE_CELLULARAUTOMATONSTATE_TIMESTAMP_2		45  /**/
#define ERR_ACN_DECODE_CELLULARAUTOMATONSTATE_STEPINDEX_2		55  /**/
#define ERR_ACN_DECODE_CELLULARAUTOMATONSTATE_ELEVATION		60  /**/
#define ERR_ACN_DECODE_CELLULARAUTOMATONSTATE_WATERDEPTH		65  /**/
flag asn1SccCellularAutomatonState_ACN_Decode(asn1SccCellularAutomatonState* pVal, BitStream* pBitStrm, int* pErrCode);
typedef char asn1SccFolderPath[256];

flag asn1SccFolderPath_Equal(const asn1SccFolderPath pVal1, const asn1SccFolderPath pVal2);

#define ERR_FOLDERPATH		71  /*(SIZE(1..255))*/
flag asn1SccFolderPath_IsConstraintValid(const asn1SccFolderPath pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccFolderPath asn1SccFolderPath_constant;
#else
#define asn1SccFolderPath_constant { [0 ... 255] = 0x0 }
#endif

void asn1SccFolderPath_Initialize(asn1SccFolderPath pVal);

#define ERR_UPER_ENCODE_FOLDERPATH		72  /**/
#define asn1SccFolderPath_REQUIRED_BYTES_FOR_ENCODING       225
#define asn1SccFolderPath_REQUIRED_BITS_FOR_ENCODING        1793

flag asn1SccFolderPath_Encode(const asn1SccFolderPath pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_FOLDERPATH		73  /**/
flag asn1SccFolderPath_Decode(asn1SccFolderPath pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccFolderPath_REQUIRED_BYTES_FOR_ACN_ENCODING       225
#define asn1SccFolderPath_REQUIRED_BITS_FOR_ACN_ENCODING        1793

#define ERR_ACN_ENCODE_FOLDERPATH		74  /**/

flag asn1SccFolderPath_ACN_Encode(const asn1SccFolderPath pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_FOLDERPATH		75  /**/
flag asn1SccFolderPath_ACN_Decode(asn1SccFolderPath pVal, BitStream* pBitStrm, int* pErrCode);
typedef enum {
    SyncMode_realTimeSkipFrames = 0,
    SyncMode_losslessAllFrames = 1
} asn1SccSyncMode;

// please use the following macros to avoid breaking code.
#define asn1SccSyncMode_realTimeSkipFrames SyncMode_realTimeSkipFrames
#define asn1SccSyncMode_losslessAllFrames SyncMode_losslessAllFrames

flag asn1SccSyncMode_Equal(const asn1SccSyncMode* pVal1, const asn1SccSyncMode* pVal2);

#define ERR_SYNCMODE		76  /*realTimeSkipFrames | losslessAllFrames*/
flag asn1SccSyncMode_IsConstraintValid(const asn1SccSyncMode* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccSyncMode asn1SccSyncMode_constant;
#else
#define asn1SccSyncMode_constant SyncMode_realTimeSkipFrames
#endif

void asn1SccSyncMode_Initialize(asn1SccSyncMode* pVal);

#define ERR_UPER_ENCODE_SYNCMODE		77  /**/
#define asn1SccSyncMode_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccSyncMode_REQUIRED_BITS_FOR_ENCODING        1

flag asn1SccSyncMode_Encode(const asn1SccSyncMode* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_SYNCMODE		78  /**/
flag asn1SccSyncMode_Decode(asn1SccSyncMode* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccSyncMode_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccSyncMode_REQUIRED_BITS_FOR_ACN_ENCODING        1

#define ERR_ACN_ENCODE_SYNCMODE		79  /**/

flag asn1SccSyncMode_ACN_Encode(const asn1SccSyncMode* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_SYNCMODE		80  /**/
flag asn1SccSyncMode_ACN_Decode(asn1SccSyncMode* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- asn1SccSimConfig --------------------------------------------*/
typedef struct {
    asn1SccFolderPath gisDataPath;
    asn1SccT_Float totalDuration;
    asn1SccT_Float timeStep;
    asn1SccT_UInt32 snapshotFreq;
    asn1SccSyncMode mode;

} asn1SccSimConfig;

flag asn1SccSimConfig_Equal(const asn1SccSimConfig* pVal1, const asn1SccSimConfig* pVal2);

#define ERR_SIMCONFIG		131  /**/
#define ERR_SIMCONFIG_GISDATAPATH_2		86  /**/
#define ERR_SIMCONFIG_TOTALDURATION_2		96  /**/
#define ERR_SIMCONFIG_TIMESTEP_2		106  /**/
#define ERR_SIMCONFIG_SNAPSHOTFREQ_2		116  /**/
#define ERR_SIMCONFIG_MODE_2		126  /**/
flag asn1SccSimConfig_IsConstraintValid(const asn1SccSimConfig* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccSimConfig asn1SccSimConfig_constant;
#else
#define asn1SccSimConfig_constant {.gisDataPath = { [0 ... 255] = 0x0 }, .totalDuration = 0.0000000000000000000E+000, .timeStep = 0.0000000000000000000E+000, .snapshotFreq = 0UL, .mode = SyncMode_realTimeSkipFrames}
#endif

void asn1SccSimConfig_Initialize(asn1SccSimConfig* pVal);

#define ERR_UPER_ENCODE_SIMCONFIG		132  /**/
#define ERR_UPER_ENCODE_SIMCONFIG_GISDATAPATH_2		87  /**/
#define ERR_UPER_ENCODE_SIMCONFIG_TOTALDURATION_2		97  /**/
#define ERR_UPER_ENCODE_SIMCONFIG_TIMESTEP_2		107  /**/
#define ERR_UPER_ENCODE_SIMCONFIG_SNAPSHOTFREQ_2		117  /**/
#define ERR_UPER_ENCODE_SIMCONFIG_MODE_2		127  /**/
#define asn1SccSimConfig_REQUIRED_BYTES_FOR_ENCODING       255
#define asn1SccSimConfig_REQUIRED_BITS_FOR_ENCODING        2034

flag asn1SccSimConfig_Encode(const asn1SccSimConfig* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_SIMCONFIG		133  /**/
#define ERR_UPER_DECODE_SIMCONFIG_GISDATAPATH_2		88  /**/
#define ERR_UPER_DECODE_SIMCONFIG_TOTALDURATION_2		98  /**/
#define ERR_UPER_DECODE_SIMCONFIG_TIMESTEP_2		108  /**/
#define ERR_UPER_DECODE_SIMCONFIG_SNAPSHOTFREQ_2		118  /**/
#define ERR_UPER_DECODE_SIMCONFIG_MODE_2		128  /**/
flag asn1SccSimConfig_Decode(asn1SccSimConfig* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccSimConfig_REQUIRED_BYTES_FOR_ACN_ENCODING       255
#define asn1SccSimConfig_REQUIRED_BITS_FOR_ACN_ENCODING        2034

#define ERR_ACN_ENCODE_SIMCONFIG		134  /**/
#define ERR_ACN_ENCODE_SIMCONFIG_GISDATAPATH_2		89  /**/
#define ERR_ACN_ENCODE_SIMCONFIG_TOTALDURATION_2		99  /**/
#define ERR_ACN_ENCODE_SIMCONFIG_TIMESTEP_2		109  /**/
#define ERR_ACN_ENCODE_SIMCONFIG_SNAPSHOTFREQ_2		119  /**/
#define ERR_ACN_ENCODE_SIMCONFIG_MODE_2		129  /**/

flag asn1SccSimConfig_ACN_Encode(const asn1SccSimConfig* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_SIMCONFIG		135  /**/
#define ERR_ACN_DECODE_SIMCONFIG_GISDATAPATH_2		90  /**/
#define ERR_ACN_DECODE_SIMCONFIG_TOTALDURATION_2		100  /**/
#define ERR_ACN_DECODE_SIMCONFIG_TIMESTEP_2		110  /**/
#define ERR_ACN_DECODE_SIMCONFIG_SNAPSHOTFREQ_2		120  /**/
#define ERR_ACN_DECODE_SIMCONFIG_MODE_2		130  /**/
flag asn1SccSimConfig_ACN_Decode(asn1SccSimConfig* pVal, BitStream* pBitStrm, int* pErrCode);
typedef enum {
    SurfaceType_soil = 0,
    SurfaceType_rock = 1,
    SurfaceType_asphalt = 2,
    SurfaceType_forest = 3,
    SurfaceType_waterSurface = 4
} asn1SccSurfaceType;

// please use the following macros to avoid breaking code.
#define asn1SccSurfaceType_soil SurfaceType_soil
#define asn1SccSurfaceType_rock SurfaceType_rock
#define asn1SccSurfaceType_asphalt SurfaceType_asphalt
#define asn1SccSurfaceType_forest SurfaceType_forest
#define asn1SccSurfaceType_waterSurface SurfaceType_waterSurface

flag asn1SccSurfaceType_Equal(const asn1SccSurfaceType* pVal1, const asn1SccSurfaceType* pVal2);

#define ERR_SURFACETYPE		136  /*soil | rock | asphalt | forest | waterSurface*/
flag asn1SccSurfaceType_IsConstraintValid(const asn1SccSurfaceType* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccSurfaceType asn1SccSurfaceType_constant;
#else
#define asn1SccSurfaceType_constant SurfaceType_soil
#endif

void asn1SccSurfaceType_Initialize(asn1SccSurfaceType* pVal);

#define ERR_UPER_ENCODE_SURFACETYPE		137  /**/
#define asn1SccSurfaceType_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccSurfaceType_REQUIRED_BITS_FOR_ENCODING        3

flag asn1SccSurfaceType_Encode(const asn1SccSurfaceType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_SURFACETYPE		138  /**/
flag asn1SccSurfaceType_Decode(asn1SccSurfaceType* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccSurfaceType_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccSurfaceType_REQUIRED_BITS_FOR_ACN_ENCODING        3

#define ERR_ACN_ENCODE_SURFACETYPE		139  /**/

flag asn1SccSurfaceType_ACN_Encode(const asn1SccSurfaceType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_SURFACETYPE		140  /**/
flag asn1SccSurfaceType_ACN_Decode(asn1SccSurfaceType* pVal, BitStream* pBitStrm, int* pErrCode);
typedef enum {
    CellType_normal = 0,
    CellType_source = 1,
    CellType_sink = 2
} asn1SccCellType;

// please use the following macros to avoid breaking code.
#define asn1SccCellType_normal CellType_normal
#define asn1SccCellType_source CellType_source
#define asn1SccCellType_sink CellType_sink

flag asn1SccCellType_Equal(const asn1SccCellType* pVal1, const asn1SccCellType* pVal2);

#define ERR_CELLTYPE		141  /*normal | source | sink*/
flag asn1SccCellType_IsConstraintValid(const asn1SccCellType* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccCellType asn1SccCellType_constant;
#else
#define asn1SccCellType_constant CellType_normal
#endif

void asn1SccCellType_Initialize(asn1SccCellType* pVal);

#define ERR_UPER_ENCODE_CELLTYPE		142  /**/
#define asn1SccCellType_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccCellType_REQUIRED_BITS_FOR_ENCODING        2

flag asn1SccCellType_Encode(const asn1SccCellType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_CELLTYPE		143  /**/
flag asn1SccCellType_Decode(asn1SccCellType* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccCellType_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccCellType_REQUIRED_BITS_FOR_ACN_ENCODING        2

#define ERR_ACN_ENCODE_CELLTYPE		144  /**/

flag asn1SccCellType_ACN_Encode(const asn1SccCellType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_CELLTYPE		145  /**/
flag asn1SccCellType_ACN_Decode(asn1SccCellType* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccSint asn1SccT_Int32;


flag asn1SccT_Int32_Equal(const asn1SccT_Int32* pVal1, const asn1SccT_Int32* pVal2);

#define ERR_T_INT32		146  /*(-2147483648 .. 2147483647)*/
flag asn1SccT_Int32_IsConstraintValid(const asn1SccT_Int32* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_Int32 asn1SccT_Int32_constant;
#else
#define asn1SccT_Int32_constant 0LL
#endif

void asn1SccT_Int32_Initialize(asn1SccT_Int32* pVal);

#define ERR_UPER_ENCODE_T_INT32		147  /**/
#define asn1SccT_Int32_REQUIRED_BYTES_FOR_ENCODING       4
#define asn1SccT_Int32_REQUIRED_BITS_FOR_ENCODING        32

flag asn1SccT_Int32_Encode(const asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_INT32		148  /**/
flag asn1SccT_Int32_Decode(asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_Int32_REQUIRED_BYTES_FOR_ACN_ENCODING       4
#define asn1SccT_Int32_REQUIRED_BITS_FOR_ACN_ENCODING        32

#define ERR_ACN_ENCODE_T_INT32		149  /**/

flag asn1SccT_Int32_ACN_Encode(const asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_INT32		150  /**/
flag asn1SccT_Int32_ACN_Decode(asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccUint asn1SccTASTE_BasicTypes_T_UInt32;


flag asn1SccTASTE_BasicTypes_T_UInt32_Equal(const asn1SccTASTE_BasicTypes_T_UInt32* pVal1, const asn1SccTASTE_BasicTypes_T_UInt32* pVal2);

#define ERR_T_UINT32_2		151  /*(0 .. 4294967294)*/
flag asn1SccTASTE_BasicTypes_T_UInt32_IsConstraintValid(const asn1SccTASTE_BasicTypes_T_UInt32* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccTASTE_BasicTypes_T_UInt32 asn1SccTASTE_BasicTypes_T_UInt32_constant;
#else
#define asn1SccTASTE_BasicTypes_T_UInt32_constant 0UL
#endif

void asn1SccTASTE_BasicTypes_T_UInt32_Initialize(asn1SccTASTE_BasicTypes_T_UInt32* pVal);

#define ERR_UPER_ENCODE_T_UINT32_2		152  /**/
#define asn1SccTASTE_BasicTypes_T_UInt32_REQUIRED_BYTES_FOR_ENCODING       4
#define asn1SccTASTE_BasicTypes_T_UInt32_REQUIRED_BITS_FOR_ENCODING        32

flag asn1SccTASTE_BasicTypes_T_UInt32_Encode(const asn1SccTASTE_BasicTypes_T_UInt32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_UINT32_2		153  /**/
flag asn1SccTASTE_BasicTypes_T_UInt32_Decode(asn1SccTASTE_BasicTypes_T_UInt32* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccTASTE_BasicTypes_T_UInt32_REQUIRED_BYTES_FOR_ACN_ENCODING       4
#define asn1SccTASTE_BasicTypes_T_UInt32_REQUIRED_BITS_FOR_ACN_ENCODING        32

#define ERR_ACN_ENCODE_T_UINT32_2		154  /**/

flag asn1SccTASTE_BasicTypes_T_UInt32_ACN_Encode(const asn1SccTASTE_BasicTypes_T_UInt32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_UINT32_2		155  /**/
flag asn1SccTASTE_BasicTypes_T_UInt32_ACN_Decode(asn1SccTASTE_BasicTypes_T_UInt32* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- asn1SccT_Runtime_Error --------------------------------------------*/

typedef enum {
    T_Runtime_Error_NONE,
    T_Runtime_Error_noerror_PRESENT,
    T_Runtime_Error_encodeerror_PRESENT,
    T_Runtime_Error_decodeerror_PRESENT
} asn1SccT_Runtime_Error_selection;

typedef union {
    asn1SccTASTE_BasicTypes_T_UInt32 noerror;
    asn1SccT_Int32 encodeerror;
    asn1SccT_Int32 decodeerror;
} asn1SccT_Runtime_Error_unchecked_union;

typedef struct {
    asn1SccT_Runtime_Error_selection kind;

    asn1SccT_Runtime_Error_unchecked_union u;
} asn1SccT_Runtime_Error;

flag asn1SccT_Runtime_Error_Equal(const asn1SccT_Runtime_Error* pVal1, const asn1SccT_Runtime_Error* pVal2);

#define ERR_T_RUNTIME_ERROR		186  /**/
#define ERR_T_RUNTIME_ERROR_NOERROR_2		161  /**/
#define ERR_T_RUNTIME_ERROR_ENCODEERROR_2		171  /**/
#define ERR_T_RUNTIME_ERROR_DECODEERROR_2		181  /**/
flag asn1SccT_Runtime_Error_IsConstraintValid(const asn1SccT_Runtime_Error* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_Runtime_Error asn1SccT_Runtime_Error_constant;
#else
#define asn1SccT_Runtime_Error_constant {.kind = T_Runtime_Error_noerror_PRESENT, .u.noerror = 0UL}
#endif

void asn1SccT_Runtime_Error_Initialize(asn1SccT_Runtime_Error* pVal);

#define ERR_UPER_ENCODE_T_RUNTIME_ERROR		187  /**/
#define ERR_UPER_ENCODE_T_RUNTIME_ERROR_NOERROR_2		162  /**/
#define ERR_UPER_ENCODE_T_RUNTIME_ERROR_ENCODEERROR_2		172  /**/
#define ERR_UPER_ENCODE_T_RUNTIME_ERROR_DECODEERROR_2		182  /**/
#define asn1SccT_Runtime_Error_REQUIRED_BYTES_FOR_ENCODING       5
#define asn1SccT_Runtime_Error_REQUIRED_BITS_FOR_ENCODING        34

flag asn1SccT_Runtime_Error_Encode(const asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_RUNTIME_ERROR		188  /**/
#define ERR_UPER_DECODE_T_RUNTIME_ERROR_NOERROR_2		163  /**/
#define ERR_UPER_DECODE_T_RUNTIME_ERROR_ENCODEERROR_2		173  /**/
#define ERR_UPER_DECODE_T_RUNTIME_ERROR_DECODEERROR_2		183  /**/
flag asn1SccT_Runtime_Error_Decode(asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_Runtime_Error_REQUIRED_BYTES_FOR_ACN_ENCODING       5
#define asn1SccT_Runtime_Error_REQUIRED_BITS_FOR_ACN_ENCODING        34

#define ERR_ACN_ENCODE_T_RUNTIME_ERROR		189  /**/
#define ERR_ACN_ENCODE_T_RUNTIME_ERROR_NOERROR_2		164  /**/
#define ERR_ACN_ENCODE_T_RUNTIME_ERROR_ENCODEERROR_2		174  /**/
#define ERR_ACN_ENCODE_T_RUNTIME_ERROR_DECODEERROR_2		184  /**/

flag asn1SccT_Runtime_Error_ACN_Encode(const asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_RUNTIME_ERROR		190  /**/
#define ERR_ACN_DECODE_T_RUNTIME_ERROR_NOERROR_2		165  /**/
#define ERR_ACN_DECODE_T_RUNTIME_ERROR_ENCODEERROR_2		175  /**/
#define ERR_ACN_DECODE_T_RUNTIME_ERROR_DECODEERROR_2		185  /**/
flag asn1SccT_Runtime_Error_ACN_Decode(asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccSint asn1SccT_Int8;


flag asn1SccT_Int8_Equal(const asn1SccT_Int8* pVal1, const asn1SccT_Int8* pVal2);

#define ERR_T_INT8		191  /*(-128 .. 127)*/
flag asn1SccT_Int8_IsConstraintValid(const asn1SccT_Int8* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_Int8 asn1SccT_Int8_constant;
#else
#define asn1SccT_Int8_constant 0LL
#endif

void asn1SccT_Int8_Initialize(asn1SccT_Int8* pVal);

#define ERR_UPER_ENCODE_T_INT8		192  /**/
#define asn1SccT_Int8_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccT_Int8_REQUIRED_BITS_FOR_ENCODING        8

flag asn1SccT_Int8_Encode(const asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_INT8		193  /**/
flag asn1SccT_Int8_Decode(asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_Int8_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccT_Int8_REQUIRED_BITS_FOR_ACN_ENCODING        8

#define ERR_ACN_ENCODE_T_INT8		194  /**/

flag asn1SccT_Int8_ACN_Encode(const asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_INT8		195  /**/
flag asn1SccT_Int8_ACN_Decode(asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccUint asn1SccT_UInt8;


flag asn1SccT_UInt8_Equal(const asn1SccT_UInt8* pVal1, const asn1SccT_UInt8* pVal2);

#define ERR_T_UINT8		196  /*(0 .. 255)*/
flag asn1SccT_UInt8_IsConstraintValid(const asn1SccT_UInt8* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_UInt8 asn1SccT_UInt8_constant;
#else
#define asn1SccT_UInt8_constant 0UL
#endif

void asn1SccT_UInt8_Initialize(asn1SccT_UInt8* pVal);

#define ERR_UPER_ENCODE_T_UINT8		197  /**/
#define asn1SccT_UInt8_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccT_UInt8_REQUIRED_BITS_FOR_ENCODING        8

flag asn1SccT_UInt8_Encode(const asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_UINT8		198  /**/
flag asn1SccT_UInt8_Decode(asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_UInt8_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccT_UInt8_REQUIRED_BITS_FOR_ACN_ENCODING        8

#define ERR_ACN_ENCODE_T_UINT8		199  /**/

flag asn1SccT_UInt8_ACN_Encode(const asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_UINT8		200  /**/
flag asn1SccT_UInt8_ACN_Decode(asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode);
typedef flag asn1SccT_Boolean;


flag asn1SccT_Boolean_Equal(const asn1SccT_Boolean* pVal1, const asn1SccT_Boolean* pVal2);

#define ERR_T_BOOLEAN		201  /**/
flag asn1SccT_Boolean_IsConstraintValid(const asn1SccT_Boolean* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_Boolean asn1SccT_Boolean_constant;
#else
#define asn1SccT_Boolean_constant FALSE
#endif

void asn1SccT_Boolean_Initialize(asn1SccT_Boolean* pVal);

#define ERR_UPER_ENCODE_T_BOOLEAN		202  /**/
#define asn1SccT_Boolean_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccT_Boolean_REQUIRED_BITS_FOR_ENCODING        1

flag asn1SccT_Boolean_Encode(const asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_T_BOOLEAN		203  /**/
flag asn1SccT_Boolean_Decode(asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_Boolean_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccT_Boolean_REQUIRED_BITS_FOR_ACN_ENCODING        1

#define ERR_ACN_ENCODE_T_BOOLEAN		204  /**/

flag asn1SccT_Boolean_ACN_Encode(const asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_T_BOOLEAN		205  /**/
flag asn1SccT_Boolean_ACN_Decode(asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- asn1SccT_Null_Record --------------------------------------------*/
typedef struct {

} asn1SccT_Null_Record;

flag asn1SccT_Null_Record_Equal(const asn1SccT_Null_Record* pVal1, const asn1SccT_Null_Record* pVal2);

#define ERR_T_NULL_RECORD		206  /**/
flag asn1SccT_Null_Record_IsConstraintValid(const asn1SccT_Null_Record* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccT_Null_Record asn1SccT_Null_Record_constant;
#else
#define asn1SccT_Null_Record_constant {}
#endif

void asn1SccT_Null_Record_Initialize(asn1SccT_Null_Record* pVal);

#define asn1SccT_Null_Record_REQUIRED_BYTES_FOR_ENCODING       0
#define asn1SccT_Null_Record_REQUIRED_BITS_FOR_ENCODING        0

flag asn1SccT_Null_Record_Encode(const asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

flag asn1SccT_Null_Record_Decode(asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccT_Null_Record_REQUIRED_BYTES_FOR_ACN_ENCODING       0
#define asn1SccT_Null_Record_REQUIRED_BITS_FOR_ACN_ENCODING        0


flag asn1SccT_Null_Record_ACN_Encode(const asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

flag asn1SccT_Null_Record_ACN_Decode(asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccUint asn1SccPID_Range;


flag asn1SccPID_Range_Equal(const asn1SccPID_Range* pVal1, const asn1SccPID_Range* pVal2);

#define ERR_PID_RANGE		211  /*(0..3)*/
flag asn1SccPID_Range_IsConstraintValid(const asn1SccPID_Range* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccPID_Range asn1SccPID_Range_constant;
#else
#define asn1SccPID_Range_constant 0UL
#endif

void asn1SccPID_Range_Initialize(asn1SccPID_Range* pVal);

#define ERR_UPER_ENCODE_PID_RANGE		212  /**/
#define asn1SccPID_Range_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccPID_Range_REQUIRED_BITS_FOR_ENCODING        2

flag asn1SccPID_Range_Encode(const asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_PID_RANGE		213  /**/
flag asn1SccPID_Range_Decode(asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccPID_Range_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccPID_Range_REQUIRED_BITS_FOR_ACN_ENCODING        2

#define ERR_ACN_ENCODE_PID_RANGE		214  /**/

flag asn1SccPID_Range_ACN_Encode(const asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_PID_RANGE		215  /**/
flag asn1SccPID_Range_ACN_Decode(asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode);
typedef enum {
    PID_coreengineca = 0,
    PID_gisdatahandler = 1,
    PID_userinterface = 2,
    PID_env = 3
} asn1SccPID;

// please use the following macros to avoid breaking code.
#define asn1SccPID_coreengineca PID_coreengineca
#define asn1SccPID_gisdatahandler PID_gisdatahandler
#define asn1SccPID_userinterface PID_userinterface
#define asn1SccPID_env PID_env

flag asn1SccPID_Equal(const asn1SccPID* pVal1, const asn1SccPID* pVal2);

#define ERR_PID		216  /*coreengineca | gisdatahandler | userinterface | env*/
flag asn1SccPID_IsConstraintValid(const asn1SccPID* pVal, int* pErrCode);

#ifdef __cplusplus
extern const asn1SccPID asn1SccPID_constant;
#else
#define asn1SccPID_constant PID_coreengineca
#endif

void asn1SccPID_Initialize(asn1SccPID* pVal);

#define ERR_UPER_ENCODE_PID		217  /**/
#define asn1SccPID_REQUIRED_BYTES_FOR_ENCODING       1
#define asn1SccPID_REQUIRED_BITS_FOR_ENCODING        2

flag asn1SccPID_Encode(const asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_PID		218  /**/
flag asn1SccPID_Decode(asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode);

#define asn1SccPID_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define asn1SccPID_REQUIRED_BITS_FOR_ACN_ENCODING        2

#define ERR_ACN_ENCODE_PID		219  /**/

flag asn1SccPID_ACN_Encode(const asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_PID		220  /**/
flag asn1SccPID_ACN_Decode(asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode);


/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */



#ifdef  __cplusplus
}

#endif

#endif
