/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>

#include "asn1crt_encoding.h"
#include "asn1crt_encoding_uper.h"
#include "asn1crt_encoding_acn.h"

#include "dataview-uniq.h"



flag asn1SccT_UInt32_Equal(const asn1SccT_UInt32* pVal1, const asn1SccT_UInt32* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccT_UInt32_IsConstraintValid(const asn1SccT_UInt32* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 4294967294UL);
    *pErrCode = ret ? 0 :  ERR_T_UINT32;

	return ret;
}

#ifdef __cplusplus
const asn1SccT_UInt32 asn1SccT_UInt32_constant = 0UL;
#endif

void asn1SccT_UInt32_Initialize(asn1SccT_UInt32* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccT_UInt32)asn1SccT_UInt32_constant;
}

flag asn1SccT_UInt32_Encode(const asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_UInt32_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 4294967294LL);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_UInt32_Decode(asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967294LL);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_T_UINT32;

	return ret  && asn1SccT_UInt32_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccT_UInt32_ACN_Encode(const asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_UInt32_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 4294967294LL);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_UInt32_ACN_Decode(asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967294LL);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_T_UINT32;

    return ret && asn1SccT_UInt32_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccT_Float_Equal(const asn1SccT_Float* pVal1, const asn1SccT_Float* pVal2)
{
	return Asn1Real_Equal((*(pVal1)),(*(pVal2)));

}

flag asn1SccT_Float_IsConstraintValid(const asn1SccT_Float* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((-2.1474836480000000000E+009 <= (*(pVal))) && ((*(pVal)) <= 2.1474836470000000000E+009));
    *pErrCode = ret ? 0 :  ERR_T_FLOAT;

	return ret;
}

#ifdef __cplusplus
const asn1SccT_Float asn1SccT_Float_constant = 0.0000000000000000000E+000;
#endif

void asn1SccT_Float_Initialize(asn1SccT_Float* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccT_Float)asn1SccT_Float_constant;
}

flag asn1SccT_Float_Encode(const asn1SccT_Float* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Float_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeReal(pBitStrm, (*(pVal)));
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Float_Decode(asn1SccT_Float* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeReal(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_T_FLOAT;

	return ret  && asn1SccT_Float_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccT_Float_ACN_Encode(const asn1SccT_Float* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Float_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeReal(pBitStrm, (*(pVal)));
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Float_ACN_Decode(asn1SccT_Float* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeReal(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_T_FLOAT;

    return ret && asn1SccT_Float_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccLayer_Equal(const asn1SccLayer* pVal1, const asn1SccLayer* pVal2)
{
	flag ret=TRUE;
    int i1;

    ret = (pVal1->nCount == pVal2->nCount);
    for(i1 = 0; ret && i1 < pVal1->nCount; i1++)
    {
    	ret = (Asn1Real_Equal(pVal1->arr[i1],pVal2->arr[i1]));
    }

	return ret;

}

flag asn1SccLayer_IsConstraintValid(const asn1SccLayer* pVal, int* pErrCode)
{
    flag ret = TRUE;
    int i1;
    ret = ((1 <= pVal->nCount) && (pVal->nCount <= 1048576));
    *pErrCode = ret ? 0 :  ERR_LAYER;
    if (ret) {
        for(i1 = 0; ret && i1 < pVal->nCount; i1++)
        {
        	ret = asn1SccT_Float_IsConstraintValid((&(pVal->arr[i1])), pErrCode);
        }
    }   /*COVERAGE_IGNORE*/

	return ret;
}

#ifdef __cplusplus
const asn1SccLayer asn1SccLayer_constant = {.nCount = 1, .arr  = {[0 ... 1048576-1] = 0.0000000000000000000E+000 }};
#endif

void asn1SccLayer_Initialize(asn1SccLayer* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccLayer)asn1SccLayer_constant;
}

flag asn1SccLayer_Encode(const asn1SccLayer* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	int i1;
	asn1SccSint nBlockIndex1;
	asn1SccSint nRemainingItemsVar1;
	asn1SccSint nCurBlockSize1;
	asn1SccSint nCurOffset1;
	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccLayer_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    nRemainingItemsVar1 = pVal->nCount;
	    nCurBlockSize1 = 0;
	    nCurOffset1 = 0;
	    nBlockIndex1 = 0;
	    while (nRemainingItemsVar1 >= 0x4000 && nBlockIndex1 < pVal->nCount)
	    {
	    	if (nRemainingItemsVar1 >= 0x10000)
	    	{
	    		nCurBlockSize1 = 0x10000;
	    		BitStream_EncodeConstraintWholeNumber(pBitStrm, 0xC4, 0, 0xFF);
	    	}
	    	else if (nRemainingItemsVar1 >= 0xC000)
	    	{
	    		nCurBlockSize1 = 0xC000;
	    		BitStream_EncodeConstraintWholeNumber(pBitStrm, 0xC3, 0, 0xFF);
	    	}
	    	else if (nRemainingItemsVar1 >= 0x8000)
	    	{
	    		nCurBlockSize1 = 0x8000;
	    		BitStream_EncodeConstraintWholeNumber(pBitStrm, 0xC2, 0, 0xFF);
	    	}
	    	else
	    	{
	    		nCurBlockSize1 = 0x4000;
	    		BitStream_EncodeConstraintWholeNumber(pBitStrm, 0xC1, 0, 0xFF);
	    	}

	    	for(i1=(int)nCurOffset1; i1 < (int)(nCurBlockSize1 + nCurOffset1); i1++)
	    	{
	    		ret = asn1SccT_Float_Encode((&(pVal->arr[i1])), pBitStrm, pErrCode, FALSE);
	    	}
	    	nCurOffset1 += nCurBlockSize1;
	    	nRemainingItemsVar1 -= nCurBlockSize1;
	        nBlockIndex1 = nBlockIndex1+1;
	    }

	    if (nRemainingItemsVar1 <= 0x7F)
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, nRemainingItemsVar1, 0, 0xFF);
	    else
	    {
	    	BitStream_AppendBit(pBitStrm, 1);
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, nRemainingItemsVar1, 0, 0x7FFF);
	    }

	    for(i1=(int)nCurOffset1; i1 < (int)(nCurOffset1 + nRemainingItemsVar1); i1++)
	    {
	    	ret = asn1SccT_Float_Encode((&(pVal->arr[i1])), pBitStrm, pErrCode, FALSE);
	    }
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccLayer_Decode(asn1SccLayer* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	int i1;
	asn1SccSint nLengthTmp1;
	asn1SccSint nRemainingItemsVar1;
	asn1SccSint nCurBlockSize1;
	asn1SccSint nCurOffset1;

	nRemainingItemsVar1 = 0;
	nCurBlockSize1 = 0;
	nCurOffset1 = 0;
	nLengthTmp1 = 0;
	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nRemainingItemsVar1, 0, 0xFF);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_LAYER;
	if (ret) {
		while(ret && (nRemainingItemsVar1 & 0xC0)==0xC0)
		{
			if (nRemainingItemsVar1 == 0xC4)
				nCurBlockSize1 = 0x10000;
			else if (nRemainingItemsVar1 == 0xC3)
				nCurBlockSize1 = 0xC000;
			else if (nRemainingItemsVar1 == 0xC2)
				nCurBlockSize1 = 0x8000;
			else if (nRemainingItemsVar1 == 0xC1)
				nCurBlockSize1 = 0x4000;
			else {
				*pErrCode = ERR_UPER_DECODE_LAYER; /*COVERAGE_IGNORE*/
				return FALSE; /*COVERAGE_IGNORE*/
			}
			if (nCurOffset1 + nCurBlockSize1 > 1048576)
			{
				*pErrCode = ERR_UPER_DECODE_LAYER; /*COVERAGE_IGNORE*/
				return FALSE; /*COVERAGE_IGNORE*/
			}

			for(i1=(int)nCurOffset1; ret && (i1 < (int)(nCurOffset1 + nCurBlockSize1)) ; i1++)
			{
				ret = asn1SccT_Float_Decode((&(pVal->arr[i1])), pBitStrm, pErrCode);
			}

	        if (ret) {
			    nLengthTmp1 += (long)nCurBlockSize1;
			    nCurOffset1 += nCurBlockSize1;
			    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nRemainingItemsVar1, 0, 0xFF);
	            *pErrCode = ret ? 0 : ERR_UPER_DECODE_LAYER;
	        }
		}
	    if (ret) {
		    if ( (nRemainingItemsVar1 & 0x80)>0)
		    {
			    asn1SccSint len2;
			    nRemainingItemsVar1 <<= 8;
			    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &len2, 0, 0xFF);
	            *pErrCode = ret ? 0 : ERR_UPER_DECODE_LAYER;
	            if (ret) {
			        nRemainingItemsVar1 |= len2;
			        nRemainingItemsVar1 &= 0x7FFF;
	            }
		    }
	        ret = ret && (nCurOffset1 + nRemainingItemsVar1 <= 1048576);
	        *pErrCode = ret ? 0 : ERR_UPER_DECODE_LAYER;
	        if (ret) {
		        for(i1=(int)nCurOffset1; ret && (i1 < (int)(nCurOffset1 + nRemainingItemsVar1)) ; i1++)
		        {
			        ret = asn1SccT_Float_Decode((&(pVal->arr[i1])), pBitStrm, pErrCode);
		        }
	            if (ret) {
		            nLengthTmp1 += (long)nRemainingItemsVar1;

	                if ((nLengthTmp1 >= 1) && (nLengthTmp1 <= 1048576)) {
		                pVal->nCount = (int)nLengthTmp1;

	                } else {
	                    ret = FALSE;  /*COVERAGE_IGNORE*/
	                    *pErrCode = ERR_UPER_DECODE_LAYER; /*COVERAGE_IGNORE*/
	                }

	            }
	        }
	    }
	}

	return ret  && asn1SccLayer_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccLayer_ACN_Encode(const asn1SccLayer* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

	int i1;
    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccLayer_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->nCount, 1, 1048576);
	    for(i1=0; (i1 < (int)pVal->nCount) && ret; i1++)
	    {
	    	ret = asn1SccT_Float_ACN_Encode((&(pVal->arr[i1])), pBitStrm, pErrCode, FALSE);
	    }
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccLayer_ACN_Decode(asn1SccLayer* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	int i1;
	asn1SccSint nCount;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 1, 1048576);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_LAYER;
	pVal->nCount = (long)nCount;
	for(i1=0; (i1 < (int)pVal->nCount) && ret; i1++)
	{
		ret = asn1SccT_Float_ACN_Decode((&(pVal->arr[i1])), pBitStrm, pErrCode);
	}

    return ret && asn1SccLayer_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccCellularAutomatonState_rows_Equal(const asn1SccCellularAutomatonState_rows* pVal1, const asn1SccCellularAutomatonState_rows* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccCellularAutomatonState_cols_Equal(const asn1SccCellularAutomatonState_cols* pVal1, const asn1SccCellularAutomatonState_cols* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccCellularAutomatonState_Equal(const asn1SccCellularAutomatonState* pVal1, const asn1SccCellularAutomatonState* pVal2)
{
	flag ret=TRUE;

    ret = asn1SccCellularAutomatonState_rows_Equal((&(pVal1->rows)), (&(pVal2->rows)));

    if (ret) {
        ret = asn1SccCellularAutomatonState_cols_Equal((&(pVal1->cols)), (&(pVal2->cols)));

        if (ret) {
            ret = (Asn1Real_Equal(pVal1->timestamp,pVal2->timestamp));

            if (ret) {
                ret = (pVal1->stepIndex == pVal2->stepIndex);

                if (ret) {
                    ret = asn1SccLayer_Equal((&(pVal1->elevation)), (&(pVal2->elevation)));

                    if (ret) {
                        ret = asn1SccLayer_Equal((&(pVal1->waterDepth)), (&(pVal2->waterDepth)));

                    }

                }

            }

        }

    }

	return ret;

}

flag asn1SccCellularAutomatonState_rows_IsConstraintValid(const asn1SccCellularAutomatonState_rows* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((1UL <= (*(pVal))) && ((*(pVal)) <= 1024UL));
    *pErrCode = ret ? 0 :  ERR_CELLULARAUTOMATONSTATE_ROWS;

	return ret;
}

flag asn1SccCellularAutomatonState_cols_IsConstraintValid(const asn1SccCellularAutomatonState_cols* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((1UL <= (*(pVal))) && ((*(pVal)) <= 1024UL));
    *pErrCode = ret ? 0 :  ERR_CELLULARAUTOMATONSTATE_COLS;

	return ret;
}

flag asn1SccCellularAutomatonState_IsConstraintValid(const asn1SccCellularAutomatonState* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = asn1SccCellularAutomatonState_rows_IsConstraintValid((&(pVal->rows)), pErrCode);
    if (ret) {
        ret = asn1SccCellularAutomatonState_cols_IsConstraintValid((&(pVal->cols)), pErrCode);
        if (ret) {
            ret = asn1SccT_Float_IsConstraintValid((&(pVal->timestamp)), pErrCode);
            if (ret) {
                ret = asn1SccT_UInt32_IsConstraintValid((&(pVal->stepIndex)), pErrCode);
                if (ret) {
                    ret = asn1SccLayer_IsConstraintValid((&(pVal->elevation)), pErrCode);
                    if (ret) {
                        ret = asn1SccLayer_IsConstraintValid((&(pVal->waterDepth)), pErrCode);
                    }   /*COVERAGE_IGNORE*/
                }   /*COVERAGE_IGNORE*/
            }   /*COVERAGE_IGNORE*/
        }   /*COVERAGE_IGNORE*/
    }   /*COVERAGE_IGNORE*/

	return ret;
}

#ifdef __cplusplus
const asn1SccCellularAutomatonState_rows asn1SccCellularAutomatonState_rows_constant = 1UL;
#endif
#ifdef __cplusplus
const asn1SccCellularAutomatonState_cols asn1SccCellularAutomatonState_cols_constant = 1UL;
#endif
#ifdef __cplusplus
const asn1SccCellularAutomatonState asn1SccCellularAutomatonState_constant = {.rows = 1UL, .cols = 1UL, .timestamp = 0.0000000000000000000E+000, .stepIndex = 0UL, .elevation = asn1SccLayer_constant, .waterDepth = asn1SccLayer_constant};
#endif

void asn1SccCellularAutomatonState_Initialize(asn1SccCellularAutomatonState* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccCellularAutomatonState)asn1SccCellularAutomatonState_constant;
}

flag asn1SccCellularAutomatonState_Encode(const asn1SccCellularAutomatonState* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccCellularAutomatonState_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode rows */
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, pVal->rows, 1, 1024);
	    if (ret) {
	        /*Encode cols */
	        BitStream_EncodeConstraintPosWholeNumber(pBitStrm, pVal->cols, 1, 1024);
	        if (ret) {
	            /*Encode timestamp */
	            ret = asn1SccT_Float_Encode((&(pVal->timestamp)), pBitStrm, pErrCode, FALSE);
	            if (ret) {
	                /*Encode stepIndex */
	                ret = asn1SccT_UInt32_Encode((&(pVal->stepIndex)), pBitStrm, pErrCode, FALSE);
	                if (ret) {
	                    /*Encode elevation */
	                    ret = asn1SccLayer_Encode((&(pVal->elevation)), pBitStrm, pErrCode, FALSE);
	                    if (ret) {
	                        /*Encode waterDepth */
	                        ret = asn1SccLayer_Encode((&(pVal->waterDepth)), pBitStrm, pErrCode, FALSE);
	                    }   /*COVERAGE_IGNORE*/
	                }   /*COVERAGE_IGNORE*/
	            }   /*COVERAGE_IGNORE*/
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccCellularAutomatonState_Decode(asn1SccCellularAutomatonState* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	/*Decode rows */
	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(pVal->rows)), 1, 1024);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_CELLULARAUTOMATONSTATE_ROWS;
	if (ret) {
	    /*Decode cols */
	    ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(pVal->cols)), 1, 1024);
	    *pErrCode = ret ? 0 : ERR_UPER_DECODE_CELLULARAUTOMATONSTATE_COLS;
	    if (ret) {
	        /*Decode timestamp */
	        ret = asn1SccT_Float_Decode((&(pVal->timestamp)), pBitStrm, pErrCode);
	        if (ret) {
	            /*Decode stepIndex */
	            ret = asn1SccT_UInt32_Decode((&(pVal->stepIndex)), pBitStrm, pErrCode);
	            if (ret) {
	                /*Decode elevation */
	                ret = asn1SccLayer_Decode((&(pVal->elevation)), pBitStrm, pErrCode);
	                if (ret) {
	                    /*Decode waterDepth */
	                    ret = asn1SccLayer_Decode((&(pVal->waterDepth)), pBitStrm, pErrCode);
	                }   /*COVERAGE_IGNORE*/
	            }   /*COVERAGE_IGNORE*/
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
	}   /*COVERAGE_IGNORE*/

	return ret  && asn1SccCellularAutomatonState_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccCellularAutomatonState_ACN_Encode(const asn1SccCellularAutomatonState* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccCellularAutomatonState_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode rows */
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, pVal->rows, 1, 1024);
	    if (ret) {
	        /*Encode cols */
	        BitStream_EncodeConstraintPosWholeNumber(pBitStrm, pVal->cols, 1, 1024);
	        if (ret) {
	            /*Encode timestamp */
	            ret = asn1SccT_Float_ACN_Encode((&(pVal->timestamp)), pBitStrm, pErrCode, FALSE);
	            if (ret) {
	                /*Encode stepIndex */
	                ret = asn1SccT_UInt32_ACN_Encode((&(pVal->stepIndex)), pBitStrm, pErrCode, FALSE);
	                if (ret) {
	                    /*Encode elevation */
	                    ret = asn1SccLayer_ACN_Encode((&(pVal->elevation)), pBitStrm, pErrCode, FALSE);
	                    if (ret) {
	                        /*Encode waterDepth */
	                        ret = asn1SccLayer_ACN_Encode((&(pVal->waterDepth)), pBitStrm, pErrCode, FALSE);
	                    }   /*COVERAGE_IGNORE*/
	                }   /*COVERAGE_IGNORE*/
	            }   /*COVERAGE_IGNORE*/
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccCellularAutomatonState_ACN_Decode(asn1SccCellularAutomatonState* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	/*Decode rows */
	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(pVal->rows)), 1, 1024);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_CELLULARAUTOMATONSTATE_ROWS;
	if (ret) {
	    /*Decode cols */
	    ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(pVal->cols)), 1, 1024);
	    *pErrCode = ret ? 0 : ERR_ACN_DECODE_CELLULARAUTOMATONSTATE_COLS;
	    if (ret) {
	        /*Decode timestamp */
	        ret = asn1SccT_Float_ACN_Decode((&(pVal->timestamp)), pBitStrm, pErrCode);
	        if (ret) {
	            /*Decode stepIndex */
	            ret = asn1SccT_UInt32_ACN_Decode((&(pVal->stepIndex)), pBitStrm, pErrCode);
	            if (ret) {
	                /*Decode elevation */
	                ret = asn1SccLayer_ACN_Decode((&(pVal->elevation)), pBitStrm, pErrCode);
	                if (ret) {
	                    /*Decode waterDepth */
	                    ret = asn1SccLayer_ACN_Decode((&(pVal->waterDepth)), pBitStrm, pErrCode);
	                }   /*COVERAGE_IGNORE*/
	            }   /*COVERAGE_IGNORE*/
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
	}   /*COVERAGE_IGNORE*/

    return ret && asn1SccCellularAutomatonState_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccFolderPath_Equal(const asn1SccFolderPath pVal1, const asn1SccFolderPath pVal2)
{
	return strcmp(pVal1, pVal2) == 0;

}

flag asn1SccFolderPath_IsConstraintValid(const asn1SccFolderPath pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((1 <= strlen(pVal)) && (strlen(pVal) <= 255));
    *pErrCode = ret ? 0 :  ERR_FOLDERPATH;

	return ret;
}

#ifdef __cplusplus
const asn1SccFolderPath asn1SccFolderPath_constant = { [0 ... 255] = 0x0 };
#endif

void asn1SccFolderPath_Initialize(asn1SccFolderPath pVal)
{
	(void)pVal;


	pVal = (asn1SccFolderPath)asn1SccFolderPath_constant;
}

flag asn1SccFolderPath_Encode(const asn1SccFolderPath pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	int i1;
	asn1SccSint nStringLength;
	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccFolderPath_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    nStringLength = strlen(pVal);
	    /*ret = nStringLength >= 1 && nStringLength <= 255;*/
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, nStringLength, 1, 255);
	    for(i1=0; (i1 < (int)nStringLength) && ret; i1++)
	    {
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal[i1], 0, 127);
	    }

    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccFolderPath_Decode(asn1SccFolderPath pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	int i1;
	asn1SccSint nStringLength;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nStringLength, 1, 255);
	for(i1=0; (i1 < (int)nStringLength) && ret; i1++)
	{
		asn1SccSint charValue=0;
		ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &charValue, 0, 127);
		*pErrCode = ret ? 0 : ERR_UPER_DECODE_FOLDERPATH;
		pVal[i1] = (char)charValue;
	}
	pVal[nStringLength] = 0x0;

	return ret  && asn1SccFolderPath_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccFolderPath_ACN_Encode(const asn1SccFolderPath pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

	int i1;
	asn1SccSint nStringLength;
    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccFolderPath_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    nStringLength = strlen(pVal);
	    /*ret = nStringLength >= 1 && nStringLength <= 255;*/
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, nStringLength, 1, 255);
	    for(i1=0; (i1 < (int)nStringLength) && ret; i1++)
	    {
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal[i1], 0, 127);
	    }

    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccFolderPath_ACN_Decode(asn1SccFolderPath pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	int i1;
	asn1SccSint nStringLength;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nStringLength, 1, 255);
	for(i1=0; (i1 < (int)nStringLength) && ret; i1++)
	{
		asn1SccSint charValue=0;
		ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &charValue, 0, 127);
		*pErrCode = ret ? 0 : ERR_ACN_DECODE_FOLDERPATH;
		pVal[i1] = (char)charValue;
	}
	pVal[nStringLength] = 0x0;

    return ret && asn1SccFolderPath_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccSyncMode_Equal(const asn1SccSyncMode* pVal1, const asn1SccSyncMode* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccSyncMode_IsConstraintValid(const asn1SccSyncMode* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((((*(pVal)) == SyncMode_realTimeSkipFrames)) || (((*(pVal)) == SyncMode_losslessAllFrames)));
    *pErrCode = ret ? 0 :  ERR_SYNCMODE;

	return ret;
}

#ifdef __cplusplus
const asn1SccSyncMode asn1SccSyncMode_constant = SyncMode_realTimeSkipFrames;
#endif

void asn1SccSyncMode_Initialize(asn1SccSyncMode* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccSyncMode)asn1SccSyncMode_constant;
}

flag asn1SccSyncMode_Encode(const asn1SccSyncMode* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccSyncMode_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    switch((*(pVal)))
	    {
	        case SyncMode_realTimeSkipFrames:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 1);
	        	break;
	        case SyncMode_losslessAllFrames:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 1);
	        	break;
	        default:                    /*COVERAGE_IGNORE*/
	    	    *pErrCode = ERR_UPER_ENCODE_SYNCMODE; /*COVERAGE_IGNORE*/
	    	    ret = FALSE;            /*COVERAGE_IGNORE*/
	    }
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccSyncMode_Decode(asn1SccSyncMode* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	{
	    asn1SccSint enumIndex;
	    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &enumIndex, 0, 1);
	    *pErrCode = ret ? 0 : ERR_UPER_DECODE_SYNCMODE;
	    if (ret) {
	        switch(enumIndex)
	        {
	            case 0:
	                (*(pVal)) = SyncMode_realTimeSkipFrames;
	                break;
	            case 1:
	                (*(pVal)) = SyncMode_losslessAllFrames;
	                break;
	            default:                        /*COVERAGE_IGNORE*/
		            *pErrCode = ERR_UPER_DECODE_SYNCMODE;     /*COVERAGE_IGNORE*/
		            ret = FALSE;                /*COVERAGE_IGNORE*/
	        }
	    } else {
	        (*(pVal)) = SyncMode_realTimeSkipFrames;             /*COVERAGE_IGNORE*/
	    }
	}

	return ret  && asn1SccSyncMode_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccSyncMode_ACN_Encode(const asn1SccSyncMode* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

	asn1SccUint intVal_pVal;
    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccSyncMode_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    switch((*(pVal))) {
	        case SyncMode_realTimeSkipFrames:
	            intVal_pVal = 0UL;
	            break;
	        case SyncMode_losslessAllFrames:
	            intVal_pVal = 1UL;
	            break;
	        default:                                    /*COVERAGE_IGNORE*/
	            ret = FALSE;                            /*COVERAGE_IGNORE*/
	            *pErrCode = ERR_ACN_ENCODE_SYNCMODE;                 /*COVERAGE_IGNORE*/
	    }
	    if (ret) {
	    	BitStream_EncodeConstraintPosWholeNumber(pBitStrm, intVal_pVal, 0, 1);
	    }
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccSyncMode_ACN_Decode(asn1SccSyncMode* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	asn1SccUint intVal_pVal;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(intVal_pVal)), 0, 1);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_SYNCMODE;
	if (ret) {
	    switch (intVal_pVal) {
	        case 0:
	            (*(pVal)) = SyncMode_realTimeSkipFrames;
	            break;
	        case 1:
	            (*(pVal)) = SyncMode_losslessAllFrames;
	            break;
	    default:                                    /*COVERAGE_IGNORE*/
	        ret = FALSE;                            /*COVERAGE_IGNORE*/
	        *pErrCode = ERR_ACN_DECODE_SYNCMODE;                 /*COVERAGE_IGNORE*/
	    }
	} /*COVERAGE_IGNORE*/

    return ret && asn1SccSyncMode_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccSimConfig_Equal(const asn1SccSimConfig* pVal1, const asn1SccSimConfig* pVal2)
{
	flag ret=TRUE;

    ret = (strcmp(pVal1->gisDataPath, pVal2->gisDataPath) == 0);

    if (ret) {
        ret = (Asn1Real_Equal(pVal1->totalDuration,pVal2->totalDuration));

        if (ret) {
            ret = (Asn1Real_Equal(pVal1->timeStep,pVal2->timeStep));

            if (ret) {
                ret = (pVal1->snapshotFreq == pVal2->snapshotFreq);

                if (ret) {
                    ret = (pVal1->mode == pVal2->mode);

                }

            }

        }

    }

	return ret;

}

flag asn1SccSimConfig_IsConstraintValid(const asn1SccSimConfig* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = asn1SccFolderPath_IsConstraintValid(pVal->gisDataPath, pErrCode);
    if (ret) {
        ret = asn1SccT_Float_IsConstraintValid((&(pVal->totalDuration)), pErrCode);
        if (ret) {
            ret = asn1SccT_Float_IsConstraintValid((&(pVal->timeStep)), pErrCode);
            if (ret) {
                ret = asn1SccT_UInt32_IsConstraintValid((&(pVal->snapshotFreq)), pErrCode);
                if (ret) {
                    ret = asn1SccSyncMode_IsConstraintValid((&(pVal->mode)), pErrCode);
                }   /*COVERAGE_IGNORE*/
            }   /*COVERAGE_IGNORE*/
        }   /*COVERAGE_IGNORE*/
    }   /*COVERAGE_IGNORE*/

	return ret;
}

#ifdef __cplusplus
const asn1SccSimConfig asn1SccSimConfig_constant = {.gisDataPath = { [0 ... 255] = 0x0 }, .totalDuration = 0.0000000000000000000E+000, .timeStep = 0.0000000000000000000E+000, .snapshotFreq = 0UL, .mode = SyncMode_realTimeSkipFrames};
#endif

void asn1SccSimConfig_Initialize(asn1SccSimConfig* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccSimConfig)asn1SccSimConfig_constant;
}

flag asn1SccSimConfig_Encode(const asn1SccSimConfig* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccSimConfig_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode gisDataPath */
	    ret = asn1SccFolderPath_Encode(pVal->gisDataPath, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode totalDuration */
	        ret = asn1SccT_Float_Encode((&(pVal->totalDuration)), pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode timeStep */
	            ret = asn1SccT_Float_Encode((&(pVal->timeStep)), pBitStrm, pErrCode, FALSE);
	            if (ret) {
	                /*Encode snapshotFreq */
	                ret = asn1SccT_UInt32_Encode((&(pVal->snapshotFreq)), pBitStrm, pErrCode, FALSE);
	                if (ret) {
	                    /*Encode mode */
	                    ret = asn1SccSyncMode_Encode((&(pVal->mode)), pBitStrm, pErrCode, FALSE);
	                }   /*COVERAGE_IGNORE*/
	            }   /*COVERAGE_IGNORE*/
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccSimConfig_Decode(asn1SccSimConfig* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	/*Decode gisDataPath */
	ret = asn1SccFolderPath_Decode(pVal->gisDataPath, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode totalDuration */
	    ret = asn1SccT_Float_Decode((&(pVal->totalDuration)), pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode timeStep */
	        ret = asn1SccT_Float_Decode((&(pVal->timeStep)), pBitStrm, pErrCode);
	        if (ret) {
	            /*Decode snapshotFreq */
	            ret = asn1SccT_UInt32_Decode((&(pVal->snapshotFreq)), pBitStrm, pErrCode);
	            if (ret) {
	                /*Decode mode */
	                ret = asn1SccSyncMode_Decode((&(pVal->mode)), pBitStrm, pErrCode);
	            }   /*COVERAGE_IGNORE*/
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
	}   /*COVERAGE_IGNORE*/

	return ret  && asn1SccSimConfig_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccSimConfig_ACN_Encode(const asn1SccSimConfig* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccSimConfig_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode gisDataPath */
	    ret = asn1SccFolderPath_ACN_Encode(pVal->gisDataPath, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode totalDuration */
	        ret = asn1SccT_Float_ACN_Encode((&(pVal->totalDuration)), pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode timeStep */
	            ret = asn1SccT_Float_ACN_Encode((&(pVal->timeStep)), pBitStrm, pErrCode, FALSE);
	            if (ret) {
	                /*Encode snapshotFreq */
	                ret = asn1SccT_UInt32_ACN_Encode((&(pVal->snapshotFreq)), pBitStrm, pErrCode, FALSE);
	                if (ret) {
	                    /*Encode mode */
	                    ret = asn1SccSyncMode_ACN_Encode((&(pVal->mode)), pBitStrm, pErrCode, FALSE);
	                }   /*COVERAGE_IGNORE*/
	            }   /*COVERAGE_IGNORE*/
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccSimConfig_ACN_Decode(asn1SccSimConfig* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	/*Decode gisDataPath */
	ret = asn1SccFolderPath_ACN_Decode(pVal->gisDataPath, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode totalDuration */
	    ret = asn1SccT_Float_ACN_Decode((&(pVal->totalDuration)), pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode timeStep */
	        ret = asn1SccT_Float_ACN_Decode((&(pVal->timeStep)), pBitStrm, pErrCode);
	        if (ret) {
	            /*Decode snapshotFreq */
	            ret = asn1SccT_UInt32_ACN_Decode((&(pVal->snapshotFreq)), pBitStrm, pErrCode);
	            if (ret) {
	                /*Decode mode */
	                ret = asn1SccSyncMode_ACN_Decode((&(pVal->mode)), pBitStrm, pErrCode);
	            }   /*COVERAGE_IGNORE*/
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
	}   /*COVERAGE_IGNORE*/

    return ret && asn1SccSimConfig_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccSurfaceType_Equal(const asn1SccSurfaceType* pVal1, const asn1SccSurfaceType* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccSurfaceType_IsConstraintValid(const asn1SccSurfaceType* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((((((((((*(pVal)) == SurfaceType_soil)) || (((*(pVal)) == SurfaceType_rock)))) || (((*(pVal)) == SurfaceType_asphalt)))) || (((*(pVal)) == SurfaceType_forest)))) || (((*(pVal)) == SurfaceType_waterSurface)));
    *pErrCode = ret ? 0 :  ERR_SURFACETYPE;

	return ret;
}

#ifdef __cplusplus
const asn1SccSurfaceType asn1SccSurfaceType_constant = SurfaceType_soil;
#endif

void asn1SccSurfaceType_Initialize(asn1SccSurfaceType* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccSurfaceType)asn1SccSurfaceType_constant;
}

flag asn1SccSurfaceType_Encode(const asn1SccSurfaceType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccSurfaceType_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    switch((*(pVal)))
	    {
	        case SurfaceType_soil:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 4);
	        	break;
	        case SurfaceType_rock:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 4);
	        	break;
	        case SurfaceType_asphalt:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 2, 0, 4);
	        	break;
	        case SurfaceType_forest:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 3, 0, 4);
	        	break;
	        case SurfaceType_waterSurface:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 4, 0, 4);
	        	break;
	        default:                    /*COVERAGE_IGNORE*/
	    	    *pErrCode = ERR_UPER_ENCODE_SURFACETYPE; /*COVERAGE_IGNORE*/
	    	    ret = FALSE;            /*COVERAGE_IGNORE*/
	    }
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccSurfaceType_Decode(asn1SccSurfaceType* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	{
	    asn1SccSint enumIndex;
	    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &enumIndex, 0, 4);
	    *pErrCode = ret ? 0 : ERR_UPER_DECODE_SURFACETYPE;
	    if (ret) {
	        switch(enumIndex)
	        {
	            case 0:
	                (*(pVal)) = SurfaceType_soil;
	                break;
	            case 1:
	                (*(pVal)) = SurfaceType_rock;
	                break;
	            case 2:
	                (*(pVal)) = SurfaceType_asphalt;
	                break;
	            case 3:
	                (*(pVal)) = SurfaceType_forest;
	                break;
	            case 4:
	                (*(pVal)) = SurfaceType_waterSurface;
	                break;
	            default:                        /*COVERAGE_IGNORE*/
		            *pErrCode = ERR_UPER_DECODE_SURFACETYPE;     /*COVERAGE_IGNORE*/
		            ret = FALSE;                /*COVERAGE_IGNORE*/
	        }
	    } else {
	        (*(pVal)) = SurfaceType_soil;             /*COVERAGE_IGNORE*/
	    }
	}

	return ret  && asn1SccSurfaceType_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccSurfaceType_ACN_Encode(const asn1SccSurfaceType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

	asn1SccUint intVal_pVal;
    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccSurfaceType_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    switch((*(pVal))) {
	        case SurfaceType_soil:
	            intVal_pVal = 0UL;
	            break;
	        case SurfaceType_rock:
	            intVal_pVal = 1UL;
	            break;
	        case SurfaceType_asphalt:
	            intVal_pVal = 2UL;
	            break;
	        case SurfaceType_forest:
	            intVal_pVal = 3UL;
	            break;
	        case SurfaceType_waterSurface:
	            intVal_pVal = 4UL;
	            break;
	        default:                                    /*COVERAGE_IGNORE*/
	            ret = FALSE;                            /*COVERAGE_IGNORE*/
	            *pErrCode = ERR_ACN_ENCODE_SURFACETYPE;                 /*COVERAGE_IGNORE*/
	    }
	    if (ret) {
	    	BitStream_EncodeConstraintPosWholeNumber(pBitStrm, intVal_pVal, 0, 4);
	    }
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccSurfaceType_ACN_Decode(asn1SccSurfaceType* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	asn1SccUint intVal_pVal;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(intVal_pVal)), 0, 4);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_SURFACETYPE;
	if (ret) {
	    switch (intVal_pVal) {
	        case 0:
	            (*(pVal)) = SurfaceType_soil;
	            break;
	        case 1:
	            (*(pVal)) = SurfaceType_rock;
	            break;
	        case 2:
	            (*(pVal)) = SurfaceType_asphalt;
	            break;
	        case 3:
	            (*(pVal)) = SurfaceType_forest;
	            break;
	        case 4:
	            (*(pVal)) = SurfaceType_waterSurface;
	            break;
	    default:                                    /*COVERAGE_IGNORE*/
	        ret = FALSE;                            /*COVERAGE_IGNORE*/
	        *pErrCode = ERR_ACN_DECODE_SURFACETYPE;                 /*COVERAGE_IGNORE*/
	    }
	} /*COVERAGE_IGNORE*/

    return ret && asn1SccSurfaceType_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccCellType_Equal(const asn1SccCellType* pVal1, const asn1SccCellType* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccCellType_IsConstraintValid(const asn1SccCellType* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((((((*(pVal)) == CellType_normal)) || (((*(pVal)) == CellType_source)))) || (((*(pVal)) == CellType_sink)));
    *pErrCode = ret ? 0 :  ERR_CELLTYPE;

	return ret;
}

#ifdef __cplusplus
const asn1SccCellType asn1SccCellType_constant = CellType_normal;
#endif

void asn1SccCellType_Initialize(asn1SccCellType* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccCellType)asn1SccCellType_constant;
}

flag asn1SccCellType_Encode(const asn1SccCellType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccCellType_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    switch((*(pVal)))
	    {
	        case CellType_normal:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 2);
	        	break;
	        case CellType_source:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 2);
	        	break;
	        case CellType_sink:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 2, 0, 2);
	        	break;
	        default:                    /*COVERAGE_IGNORE*/
	    	    *pErrCode = ERR_UPER_ENCODE_CELLTYPE; /*COVERAGE_IGNORE*/
	    	    ret = FALSE;            /*COVERAGE_IGNORE*/
	    }
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccCellType_Decode(asn1SccCellType* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	{
	    asn1SccSint enumIndex;
	    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &enumIndex, 0, 2);
	    *pErrCode = ret ? 0 : ERR_UPER_DECODE_CELLTYPE;
	    if (ret) {
	        switch(enumIndex)
	        {
	            case 0:
	                (*(pVal)) = CellType_normal;
	                break;
	            case 1:
	                (*(pVal)) = CellType_source;
	                break;
	            case 2:
	                (*(pVal)) = CellType_sink;
	                break;
	            default:                        /*COVERAGE_IGNORE*/
		            *pErrCode = ERR_UPER_DECODE_CELLTYPE;     /*COVERAGE_IGNORE*/
		            ret = FALSE;                /*COVERAGE_IGNORE*/
	        }
	    } else {
	        (*(pVal)) = CellType_normal;             /*COVERAGE_IGNORE*/
	    }
	}

	return ret  && asn1SccCellType_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccCellType_ACN_Encode(const asn1SccCellType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

	asn1SccUint intVal_pVal;
    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccCellType_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    switch((*(pVal))) {
	        case CellType_normal:
	            intVal_pVal = 0UL;
	            break;
	        case CellType_source:
	            intVal_pVal = 1UL;
	            break;
	        case CellType_sink:
	            intVal_pVal = 2UL;
	            break;
	        default:                                    /*COVERAGE_IGNORE*/
	            ret = FALSE;                            /*COVERAGE_IGNORE*/
	            *pErrCode = ERR_ACN_ENCODE_CELLTYPE;                 /*COVERAGE_IGNORE*/
	    }
	    if (ret) {
	    	BitStream_EncodeConstraintPosWholeNumber(pBitStrm, intVal_pVal, 0, 2);
	    }
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccCellType_ACN_Decode(asn1SccCellType* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	asn1SccUint intVal_pVal;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(intVal_pVal)), 0, 2);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_CELLTYPE;
	if (ret) {
	    switch (intVal_pVal) {
	        case 0:
	            (*(pVal)) = CellType_normal;
	            break;
	        case 1:
	            (*(pVal)) = CellType_source;
	            break;
	        case 2:
	            (*(pVal)) = CellType_sink;
	            break;
	    default:                                    /*COVERAGE_IGNORE*/
	        ret = FALSE;                            /*COVERAGE_IGNORE*/
	        *pErrCode = ERR_ACN_DECODE_CELLTYPE;                 /*COVERAGE_IGNORE*/
	    }
	} /*COVERAGE_IGNORE*/

    return ret && asn1SccCellType_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccT_Int32_Equal(const asn1SccT_Int32* pVal1, const asn1SccT_Int32* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccT_Int32_IsConstraintValid(const asn1SccT_Int32* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((-2147483648LL <= (*(pVal))) && ((*(pVal)) <= 2147483647LL));
    *pErrCode = ret ? 0 :  ERR_T_INT32;

	return ret;
}

#ifdef __cplusplus
const asn1SccT_Int32 asn1SccT_Int32_constant = 0LL;
#endif

void asn1SccT_Int32_Initialize(asn1SccT_Int32* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccT_Int32)asn1SccT_Int32_constant;
}

flag asn1SccT_Int32_Encode(const asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Int32_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, (*(pVal)), -2147483648LL, 2147483647LL);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Int32_Decode(asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, pVal, -2147483648LL, 2147483647LL);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_T_INT32;

	return ret  && asn1SccT_Int32_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccT_Int32_ACN_Encode(const asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Int32_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, (*(pVal)), -2147483648LL, 2147483647LL);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Int32_ACN_Decode(asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, pVal, -2147483648LL, 2147483647LL);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_T_INT32;

    return ret && asn1SccT_Int32_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccTASTE_BasicTypes_T_UInt32_Equal(const asn1SccTASTE_BasicTypes_T_UInt32* pVal1, const asn1SccTASTE_BasicTypes_T_UInt32* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccTASTE_BasicTypes_T_UInt32_IsConstraintValid(const asn1SccTASTE_BasicTypes_T_UInt32* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 4294967294UL);
    *pErrCode = ret ? 0 :  ERR_T_UINT32_2;

	return ret;
}

#ifdef __cplusplus
const asn1SccTASTE_BasicTypes_T_UInt32 asn1SccTASTE_BasicTypes_T_UInt32_constant = 0UL;
#endif

void asn1SccTASTE_BasicTypes_T_UInt32_Initialize(asn1SccTASTE_BasicTypes_T_UInt32* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccTASTE_BasicTypes_T_UInt32)asn1SccTASTE_BasicTypes_T_UInt32_constant;
}

flag asn1SccTASTE_BasicTypes_T_UInt32_Encode(const asn1SccTASTE_BasicTypes_T_UInt32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccTASTE_BasicTypes_T_UInt32_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 4294967294LL);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccTASTE_BasicTypes_T_UInt32_Decode(asn1SccTASTE_BasicTypes_T_UInt32* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967294LL);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_T_UINT32_2;

	return ret  && asn1SccTASTE_BasicTypes_T_UInt32_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccTASTE_BasicTypes_T_UInt32_ACN_Encode(const asn1SccTASTE_BasicTypes_T_UInt32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccTASTE_BasicTypes_T_UInt32_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 4294967294LL);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccTASTE_BasicTypes_T_UInt32_ACN_Decode(asn1SccTASTE_BasicTypes_T_UInt32* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967294LL);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_T_UINT32_2;

    return ret && asn1SccTASTE_BasicTypes_T_UInt32_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccT_Runtime_Error_Equal(const asn1SccT_Runtime_Error* pVal1, const asn1SccT_Runtime_Error* pVal2)
{
	flag ret=TRUE;

    ret = (pVal1->kind == pVal2->kind);
    if (ret) {
    	switch(pVal1->kind)
    	{
    	case T_Runtime_Error_noerror_PRESENT:
    		ret = (pVal1->u.noerror == pVal2->u.noerror);
    		break;
    	case T_Runtime_Error_encodeerror_PRESENT:
    		ret = (pVal1->u.encodeerror == pVal2->u.encodeerror);
    		break;
    	case T_Runtime_Error_decodeerror_PRESENT:
    		ret = (pVal1->u.decodeerror == pVal2->u.decodeerror);
    		break;
    	default: /*COVERAGE_IGNORE*/
    		ret = FALSE;    /*COVERAGE_IGNORE*/
    	}
    } /*COVERAGE_IGNORE*/
	return ret;

}

flag asn1SccT_Runtime_Error_IsConstraintValid(const asn1SccT_Runtime_Error* pVal, int* pErrCode)
{
    flag ret = TRUE;
    switch (pVal->kind) {
        case T_Runtime_Error_noerror_PRESENT : 
            ret = asn1SccTASTE_BasicTypes_T_UInt32_IsConstraintValid((&(pVal->u.noerror)), pErrCode);
            break;          
        case T_Runtime_Error_encodeerror_PRESENT : 
            ret = asn1SccT_Int32_IsConstraintValid((&(pVal->u.encodeerror)), pErrCode);
            break;          
        case T_Runtime_Error_decodeerror_PRESENT : 
            ret = asn1SccT_Int32_IsConstraintValid((&(pVal->u.decodeerror)), pErrCode);
            break;          
        default: /*COVERAGE_IGNORE*/
    	    *pErrCode = ERR_T_RUNTIME_ERROR;      /*COVERAGE_IGNORE*/
    	    ret = FALSE;                               /*COVERAGE_IGNORE*/
    }

	return ret;
}

#ifdef __cplusplus
const asn1SccT_Runtime_Error asn1SccT_Runtime_Error_constant = {.kind = T_Runtime_Error_noerror_PRESENT, .u.noerror = 0UL};
#endif

void asn1SccT_Runtime_Error_Initialize(asn1SccT_Runtime_Error* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccT_Runtime_Error)asn1SccT_Runtime_Error_constant;
}

flag asn1SccT_Runtime_Error_Encode(const asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Runtime_Error_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    switch(pVal->kind)
	    {
	    case T_Runtime_Error_noerror_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 2);
	    	ret = asn1SccTASTE_BasicTypes_T_UInt32_Encode((&(pVal->u.noerror)), pBitStrm, pErrCode, FALSE);
	    	break;
	    case T_Runtime_Error_encodeerror_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 2);
	    	ret = asn1SccT_Int32_Encode((&(pVal->u.encodeerror)), pBitStrm, pErrCode, FALSE);
	    	break;
	    case T_Runtime_Error_decodeerror_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 2, 0, 2);
	    	ret = asn1SccT_Int32_Encode((&(pVal->u.decodeerror)), pBitStrm, pErrCode, FALSE);
	    	break;
	    default:                            /*COVERAGE_IGNORE*/
	        *pErrCode = ERR_UPER_ENCODE_T_RUNTIME_ERROR;         /*COVERAGE_IGNORE*/
	        ret = FALSE;                    /*COVERAGE_IGNORE*/
	    }
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Runtime_Error_Decode(asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	asn1SccSint asn1SccT_Runtime_Error_index_tmp;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &asn1SccT_Runtime_Error_index_tmp, 0, 2);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_T_RUNTIME_ERROR;
	if (ret) {
	    switch(asn1SccT_Runtime_Error_index_tmp)
	    {
	    case 0:
	    	pVal->kind = T_Runtime_Error_noerror_PRESENT;
	    	ret = asn1SccTASTE_BasicTypes_T_UInt32_Decode((&(pVal->u.noerror)), pBitStrm, pErrCode);
	    	break;
	    case 1:
	    	pVal->kind = T_Runtime_Error_encodeerror_PRESENT;
	    	ret = asn1SccT_Int32_Decode((&(pVal->u.encodeerror)), pBitStrm, pErrCode);
	    	break;
	    case 2:
	    	pVal->kind = T_Runtime_Error_decodeerror_PRESENT;
	    	ret = asn1SccT_Int32_Decode((&(pVal->u.decodeerror)), pBitStrm, pErrCode);
	    	break;
	    default:                        /*COVERAGE_IGNORE*/
	        *pErrCode = ERR_UPER_DECODE_T_RUNTIME_ERROR;     /*COVERAGE_IGNORE*/
	        ret = FALSE;                /*COVERAGE_IGNORE*/
	    }
	}  /*COVERAGE_IGNORE*/

	return ret  && asn1SccT_Runtime_Error_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccT_Runtime_Error_ACN_Encode(const asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Runtime_Error_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    switch(pVal->kind)
	    {
	    case T_Runtime_Error_noerror_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 2);
	    	ret = asn1SccTASTE_BasicTypes_T_UInt32_ACN_Encode((&(pVal->u.noerror)), pBitStrm, pErrCode, FALSE);
	    	break;
	    case T_Runtime_Error_encodeerror_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 2);
	    	ret = asn1SccT_Int32_ACN_Encode((&(pVal->u.encodeerror)), pBitStrm, pErrCode, FALSE);
	    	break;
	    case T_Runtime_Error_decodeerror_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 2, 0, 2);
	    	ret = asn1SccT_Int32_ACN_Encode((&(pVal->u.decodeerror)), pBitStrm, pErrCode, FALSE);
	    	break;
	    default: /*COVERAGE_IGNORE*/
	        *pErrCode = ERR_ACN_ENCODE_T_RUNTIME_ERROR;         /*COVERAGE_IGNORE*/
	        ret = FALSE;                    /*COVERAGE_IGNORE*/
	    } /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Runtime_Error_ACN_Decode(asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	asn1SccSint TASTE_BasicTypes_T_Runtime_Error_index_tmp;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &TASTE_BasicTypes_T_Runtime_Error_index_tmp, 0, 2);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_T_RUNTIME_ERROR;
	if (ret) {
	    switch(TASTE_BasicTypes_T_Runtime_Error_index_tmp)
	    {
	    case 0:
	    	pVal->kind = T_Runtime_Error_noerror_PRESENT;
	    	ret = asn1SccTASTE_BasicTypes_T_UInt32_ACN_Decode((&(pVal->u.noerror)), pBitStrm, pErrCode);
	    	break;
	    case 1:
	    	pVal->kind = T_Runtime_Error_encodeerror_PRESENT;
	    	ret = asn1SccT_Int32_ACN_Decode((&(pVal->u.encodeerror)), pBitStrm, pErrCode);
	    	break;
	    case 2:
	    	pVal->kind = T_Runtime_Error_decodeerror_PRESENT;
	    	ret = asn1SccT_Int32_ACN_Decode((&(pVal->u.decodeerror)), pBitStrm, pErrCode);
	    	break;
	    default: /*COVERAGE_IGNORE*/
	        *pErrCode = ERR_ACN_DECODE_T_RUNTIME_ERROR;     /*COVERAGE_IGNORE*/
	        ret = FALSE;                /*COVERAGE_IGNORE*/
	    }
	} /*COVERAGE_IGNORE*/

    return ret && asn1SccT_Runtime_Error_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccT_Int8_Equal(const asn1SccT_Int8* pVal1, const asn1SccT_Int8* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccT_Int8_IsConstraintValid(const asn1SccT_Int8* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((-128LL <= (*(pVal))) && ((*(pVal)) <= 127LL));
    *pErrCode = ret ? 0 :  ERR_T_INT8;

	return ret;
}

#ifdef __cplusplus
const asn1SccT_Int8 asn1SccT_Int8_constant = 0LL;
#endif

void asn1SccT_Int8_Initialize(asn1SccT_Int8* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccT_Int8)asn1SccT_Int8_constant;
}

flag asn1SccT_Int8_Encode(const asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Int8_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, (*(pVal)), -128, 127);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Int8_Decode(asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, pVal, -128, 127);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_T_INT8;

	return ret  && asn1SccT_Int8_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccT_Int8_ACN_Encode(const asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Int8_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, (*(pVal)), -128, 127);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Int8_ACN_Decode(asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, pVal, -128, 127);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_T_INT8;

    return ret && asn1SccT_Int8_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccT_UInt8_Equal(const asn1SccT_UInt8* pVal1, const asn1SccT_UInt8* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccT_UInt8_IsConstraintValid(const asn1SccT_UInt8* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 255UL);
    *pErrCode = ret ? 0 :  ERR_T_UINT8;

	return ret;
}

#ifdef __cplusplus
const asn1SccT_UInt8 asn1SccT_UInt8_constant = 0UL;
#endif

void asn1SccT_UInt8_Initialize(asn1SccT_UInt8* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccT_UInt8)asn1SccT_UInt8_constant;
}

flag asn1SccT_UInt8_Encode(const asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_UInt8_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 255);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_UInt8_Decode(asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 255);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_T_UINT8;

	return ret  && asn1SccT_UInt8_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccT_UInt8_ACN_Encode(const asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_UInt8_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 255);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_UInt8_ACN_Decode(asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 255);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_T_UINT8;

    return ret && asn1SccT_UInt8_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccT_Boolean_Equal(const asn1SccT_Boolean* pVal1, const asn1SccT_Boolean* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccT_Boolean_IsConstraintValid(const asn1SccT_Boolean* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
    ret = TRUE;
    *pErrCode = 0;

	return ret;
}

#ifdef __cplusplus
const asn1SccT_Boolean asn1SccT_Boolean_constant = FALSE;
#endif

void asn1SccT_Boolean_Initialize(asn1SccT_Boolean* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccT_Boolean)asn1SccT_Boolean_constant;
}

flag asn1SccT_Boolean_Encode(const asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Boolean_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_AppendBit(pBitStrm,(*(pVal)));
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Boolean_Decode(asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_ReadBit(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_T_BOOLEAN;

	return ret  && asn1SccT_Boolean_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccT_Boolean_ACN_Encode(const asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Boolean_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_AppendBit(pBitStrm,(*(pVal)));
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Boolean_ACN_Decode(asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_ReadBit(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_T_BOOLEAN;

    return ret && asn1SccT_Boolean_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccT_Null_Record_Equal(const asn1SccT_Null_Record* pVal1, const asn1SccT_Null_Record* pVal2)
{
	(void)pVal1;
	(void)pVal2;
	return TRUE;

}

flag asn1SccT_Null_Record_IsConstraintValid(const asn1SccT_Null_Record* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
    ret = TRUE;
    *pErrCode = 0;

	return ret;
}

#ifdef __cplusplus
const asn1SccT_Null_Record asn1SccT_Null_Record_constant = {};
#endif

void asn1SccT_Null_Record_Initialize(asn1SccT_Null_Record* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccT_Null_Record)asn1SccT_Null_Record_constant;
}

flag asn1SccT_Null_Record_Encode(const asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	(void)pBitStrm;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Null_Record_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Null_Record_Decode(asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;
	(void)pBitStrm;



	return ret  && asn1SccT_Null_Record_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccT_Null_Record_ACN_Encode(const asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	(void)pBitStrm;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Null_Record_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Null_Record_ACN_Decode(asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	(void)pBitStrm;
	*pErrCode = 0;



    return ret && asn1SccT_Null_Record_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccPID_Range_Equal(const asn1SccPID_Range* pVal1, const asn1SccPID_Range* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccPID_Range_IsConstraintValid(const asn1SccPID_Range* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 3UL);
    *pErrCode = ret ? 0 :  ERR_PID_RANGE;

	return ret;
}

#ifdef __cplusplus
const asn1SccPID_Range asn1SccPID_Range_constant = 0UL;
#endif

void asn1SccPID_Range_Initialize(asn1SccPID_Range* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccPID_Range)asn1SccPID_Range_constant;
}

flag asn1SccPID_Range_Encode(const asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccPID_Range_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 3);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccPID_Range_Decode(asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 3);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_PID_RANGE;

	return ret  && asn1SccPID_Range_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccPID_Range_ACN_Encode(const asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccPID_Range_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 3);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccPID_Range_ACN_Decode(asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 3);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_PID_RANGE;

    return ret && asn1SccPID_Range_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccPID_Equal(const asn1SccPID* pVal1, const asn1SccPID* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccPID_IsConstraintValid(const asn1SccPID* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((((((((*(pVal)) == PID_coreengineca)) || (((*(pVal)) == PID_gisdatahandler)))) || (((*(pVal)) == PID_userinterface)))) || (((*(pVal)) == PID_env)));
    *pErrCode = ret ? 0 :  ERR_PID;

	return ret;
}

#ifdef __cplusplus
const asn1SccPID asn1SccPID_constant = PID_coreengineca;
#endif

void asn1SccPID_Initialize(asn1SccPID* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccPID)asn1SccPID_constant;
}

flag asn1SccPID_Encode(const asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccPID_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    switch((*(pVal)))
	    {
	        case PID_coreengineca:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 3);
	        	break;
	        case PID_gisdatahandler:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 3);
	        	break;
	        case PID_userinterface:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 2, 0, 3);
	        	break;
	        case PID_env:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 3, 0, 3);
	        	break;
	        default:                    /*COVERAGE_IGNORE*/
	    	    *pErrCode = ERR_UPER_ENCODE_PID; /*COVERAGE_IGNORE*/
	    	    ret = FALSE;            /*COVERAGE_IGNORE*/
	    }
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccPID_Decode(asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	{
	    asn1SccSint enumIndex;
	    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &enumIndex, 0, 3);
	    *pErrCode = ret ? 0 : ERR_UPER_DECODE_PID;
	    if (ret) {
	        switch(enumIndex)
	        {
	            case 0:
	                (*(pVal)) = PID_coreengineca;
	                break;
	            case 1:
	                (*(pVal)) = PID_gisdatahandler;
	                break;
	            case 2:
	                (*(pVal)) = PID_userinterface;
	                break;
	            case 3:
	                (*(pVal)) = PID_env;
	                break;
	            default:                        /*COVERAGE_IGNORE*/
		            *pErrCode = ERR_UPER_DECODE_PID;     /*COVERAGE_IGNORE*/
		            ret = FALSE;                /*COVERAGE_IGNORE*/
	        }
	    } else {
	        (*(pVal)) = PID_coreengineca;             /*COVERAGE_IGNORE*/
	    }
	}

	return ret  && asn1SccPID_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccPID_ACN_Encode(const asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

	asn1SccUint intVal_pVal;
    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccPID_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    switch((*(pVal))) {
	        case PID_coreengineca:
	            intVal_pVal = 0UL;
	            break;
	        case PID_gisdatahandler:
	            intVal_pVal = 1UL;
	            break;
	        case PID_userinterface:
	            intVal_pVal = 2UL;
	            break;
	        case PID_env:
	            intVal_pVal = 3UL;
	            break;
	        default:                                    /*COVERAGE_IGNORE*/
	            ret = FALSE;                            /*COVERAGE_IGNORE*/
	            *pErrCode = ERR_ACN_ENCODE_PID;                 /*COVERAGE_IGNORE*/
	    }
	    if (ret) {
	    	BitStream_EncodeConstraintPosWholeNumber(pBitStrm, intVal_pVal, 0, 3);
	    }
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccPID_ACN_Decode(asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	asn1SccUint intVal_pVal;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(intVal_pVal)), 0, 3);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_PID;
	if (ret) {
	    switch (intVal_pVal) {
	        case 0:
	            (*(pVal)) = PID_coreengineca;
	            break;
	        case 1:
	            (*(pVal)) = PID_gisdatahandler;
	            break;
	        case 2:
	            (*(pVal)) = PID_userinterface;
	            break;
	        case 3:
	            (*(pVal)) = PID_env;
	            break;
	    default:                                    /*COVERAGE_IGNORE*/
	        ret = FALSE;                            /*COVERAGE_IGNORE*/
	        *pErrCode = ERR_ACN_DECODE_PID;                 /*COVERAGE_IGNORE*/
	    }
	} /*COVERAGE_IGNORE*/

    return ret && asn1SccPID_IsConstraintValid(pVal, pErrCode);
}


