#ifndef __PRINTTYPESASASN1_H__
#define __PRINTTYPESASASN1_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "dataview-uniq.h" // Generated by ASN1SCC

void PrintASN1T_UInt32(const char *paramName, const asn1SccT_UInt32 *pData);
void PrintASN1Duration(const char *paramName, const asn1SccDuration *pData);
void PrintASN1TimeStep(const char *paramName, const asn1SccTimeStep *pData);
void PrintASN1Height(const char *paramName, const asn1SccHeight *pData);
void PrintASN1SurfaceType(const char *paramName, const asn1SccSurfaceType *pData);
void PrintASN1CellState(const char *paramName, const asn1SccCellState *pData);
void PrintASN1GridVector(const char *paramName, const asn1SccGridVector *pData);
void PrintASN1Grid(const char *paramName, const asn1SccGrid *pData);
void PrintASN1FlowCoefficient(const char *paramName, const asn1SccFlowCoefficient *pData);
void PrintASN1ScaleFactor(const char *paramName, const asn1SccScaleFactor *pData);
void PrintASN1FilePath(const char *paramName, const asn1SccFilePath *pData);
void PrintASN1CellIndex(const char *paramName, const asn1SccCellIndex *pData);
void PrintASN1Outflow(const char *paramName, const asn1SccOutflow *pData);
void PrintASN1OutflowList(const char *paramName, const asn1SccOutflowList *pData);
void PrintASN1MooreNeighborList(const char *paramName, const asn1SccMooreNeighborList *pData);
void PrintASN1GridCellNeighborList(const char *paramName, const asn1SccGridCellNeighborList *pData);
void PrintASN1FlowingWaterEvent(const char *paramName, const asn1SccFlowingWaterEvent *pData);
void PrintASN1FlowingWaterEventList(const char *paramName, const asn1SccFlowingWaterEventList *pData);
void PrintASN1GridModification(const char *paramName, const asn1SccGridModification *pData);
void PrintASN1GridModificationList(const char *paramName, const asn1SccGridModificationList *pData);
void PrintASN1MooreNeighborIndex(const char *paramName, const asn1SccMooreNeighborIndex *pData);
void PrintASN1T_Int32(const char *paramName, const asn1SccT_Int32 *pData);
void PrintASN1TASTE_BasicTypes_T_UInt32(const char *paramName, const asn1SccTASTE_BasicTypes_T_UInt32 *pData);
void PrintASN1T_Runtime_Error(const char *paramName, const asn1SccT_Runtime_Error *pData);
void PrintASN1T_Int8(const char *paramName, const asn1SccT_Int8 *pData);
void PrintASN1T_UInt8(const char *paramName, const asn1SccT_UInt8 *pData);
void PrintASN1T_Boolean(const char *paramName, const asn1SccT_Boolean *pData);
void PrintASN1T_Null_Record(const char *paramName, const asn1SccT_Null_Record *pData);
void PrintASN1PID_Range(const char *paramName, const asn1SccPID_Range *pData);
void PrintASN1PID(const char *paramName, const asn1SccPID *pData);

#ifdef __cplusplus
}
#endif

#endif
